### ISSUE TITLE
Sharing MDS data for applied research

### ISSUE THREAD

**Issue by patwater** [openmobilityfoundation/mobility-data-specification#136]
Loved the presentation today! Zero rush though would be curious on what the timeline is for enabling access to MDS data to academic and nonprofit research teams. 

Lots of fascinating social science questions that could be addressed with this dataset. Also lots of urban planning benefits and applied R&D that could be done. I would also be curious to see if accelerometer data could be integrated into MDS as a measure of street quality. 

As Boston's Street Bump experiment showed, accelerometer data is great for detecting potholes though has false defect positives with street hardware and false negatives with cracking. Note that a key benefit here with scooters is the ability to get a measure of ride quality on sidewalks and bike lanes -- the [maintenance of which is a multi-million issue and liability for cities. ](https://www.kcet.org/shows/socal-connected/cycle-of-disrepair)

There's also broader planning benefits from streamlining data sharing for research. Imagine for example the not too distant future where there's mobility service providers (not just shared e-scooters though also larger AVs) operating across the entire Southland. Important to have data to manage and start planning for that today. 

Definitely needs to be sensitive to privacy considerations with trip level data (even if its just a device and not a user ID -- see the NYC taxi dataset for a cautionary tale) though those can definitely be addressed ethically and pragmatically.

**Comment by schnuerle** [comment]
I think this is going to happen only via data sharing agreements between cities/providers and research institutions. 

Another option right now is to look at published data on city open data websites: https://github.com/openmobilityfoundation/privacy-committee/blob/main/products/state-of-the-practice.md
