### ISSUE TITLE
autogenerate docs from JSON Schema

### ISSUE THREAD

**Issue by hunterowens** [openmobilityfoundation/mobility-data-specification#141]
per @cttengsfmta, it probably makes sense to have something that autogenerates the "human readable" files from JSONSchema. Ie, `generate_schema.py`  -> `trips.md`. this would help prevent the validators from getting out of sync with the written messages.

**Comment by thekaveman** [comment]
Recent work on [`mds-provider`](https://github.com/CityofSantaMonica/mds-provider/pull/18) added functionality for obtaining and parsing through the schemas. This could be a way to get the tokens, descriptions, etc. from the schemas into code, for doc generation.

**Comment by thekaveman** [comment]
@drernie definitely still of interest. Feel free to submit a PR, even if you're just exploring some ideas, to get a discussion going.

**Comment by schnuerle** [comment]
I believe we have now created this with our OpenAPI work in this [new repo](https://github.com/openmobilityfoundation/mds-openapi) and autogenerated [interactive docs](https://openmobilityfnd.stoplight.io/docs/mds-openapi).
