### ISSUE TITLE
Agency:  Seperate TNC / Fleet Owner

### ISSUE THREAD

**Issue by toddapetersen** [openmobilityfoundation/mobility-data-specification#157]
The Agency does not contemplate having a separate fleet manager (currently provider_id) and TNC.   We may need to add a provider_ID and potentially TNC_id  when starting / ending trips or issue provider_id to both providers and TNCs.

**Comment by HenriJ** [comment]
@toddapetersen Is this issue still relevant ?

**Comment by toddapetersen** [comment]
Seems like we have moved past this.   We can close it out.   Thanks for asking.
