### ISSUE TITLE
Agency: Additional event_types

### ISSUE THREAD

**Issue by lionel-panhaleux** [openmobilityfoundation/mobility-data-specification#274]
Some sensible transitions are missing from `event_types`.

A vehicle can be put back in the street at the end of a trip, a maintenance or a rebalancing, but be unavailable for the time being. I propose to add `trip_end_available` and `provider_drop_off_unavailable` event types (this may not be the best naming for these transitions, do not hesitate to provide alternatives)

This is especially true for electrically powered devices, as it makes sense for the vehicles to be `unavailable` by default, until the battery status is checked and the provider makes sure the vehicle can be made available again. For now, BlueLA  has to send successive events on the agency API to express this, which is not ideal.

I'll attach a PR to this issue, unfortunately I have no access to the source file for the state machine diagram and was unable to provide a new diagram along. Including the source of the diagram may be of use for other contributors ?

What do you think ? Thanks in advance for your comments.

**Comment by karcass** [comment]
It's worth considering.  For 0.3.x, we will stick with using multiple events to capture these types of transitions.  We should gather feedback from all the providers before we add additional events.

**Comment by Retzoh** [comment]
I can follow up on this

**Comment by Retzoh** [comment]
@sarob as discussed in the city-services working group, this issue should be moved to the 0.5.0 milestone.

It should hopefully be solved by #271 .

**Comment by schnuerle** [comment]
I believe this is resolved with #271 for release 1.0.0.  Please let us know if this does not address your concerns.
