### ISSUE TITLE
Include links to old version of MDS provider from provider page

### ISSUE THREAD

**Issue by craastad** [openmobilityfoundation/mobility-data-specification#318]
### Is your feature request related to a problem? Please describe.

Coming into MDS development during the transition between MDS 0.2 and 0.3 without much experience of navigating the versions, I struggled to keep the versions of the API in order and implemented a few bugs as result of the changes between 0.2 and 0.3. Non technical people getting links to the github repository or searching from Google, unfamiliar with github release, branches, and tags, have a hard time finding exactly the specification of version X.Y.Z of the APIs including necessary names and details of the parameters (i.e. miliseconds vs. seconds).

Currently navigating to the [MDS github page](https://github.com/CityOfLosAngeles/mobility-data-specification) and to the [Provider API Page](https://github.com/CityOfLosAngeles/mobility-data-specification/blob/dev/provider/README.md) defaults to the dev branch, which may be ahead of the latest [master release](https://github.com/CityOfLosAngeles/mobility-data-specification/blob/master/provider/README.md) or previous versions.

In order to visit previous versions of the API, one needs to do the following:
 * have knowledge of github tags and navigate to the correct version (e.g. [0.2.1](https://github.com/CityOfLosAngeles/mobility-data-specification/tree/0.2.1)).
* then click the [MDS Provider link](https://github.com/CityOfLosAngeles/mobility-data-specification/blob/0.2.1/provider/README.md)
 * ~~navigate to the [releases page](https://github.com/CityOfLosAngeles/mobility-data-specification/releases)~~
* ~~click the hash of the commit under the version (i.e. [253aaa9](https://github.com/CityOfLosAngeles/mobility-data-specification/commit/253aaa94cbd5cc35486e9787d5d48ce3c0d04e74) for version 0.2.1)~~
* ~~click [browse files](https://github.com/CityOfLosAngeles/mobility-data-specification/tree/253aaa94cbd5cc35486e9787d5d48ce3c0d04e74)~~
* ~~then click the [MDS Provider link](https://github.com/CityOfLosAngeles/mobility-data-specification/blob/253aaa94cbd5cc35486e9787d5d48ce3c0d04e74/provider/README.md)~~

Once on this page, the only indication of the version is in the tag URL ~~there is no indication of which version of the API is being displayed in the READMEs or in the URLs (which are commit hashes)~~.

### Describe the solution you'd like

I propose two ~three~ changes to improve version navigation:

(1) Explicitly state the MDS version (i.e. 0.3.1) in the title or subtitle of the root [README.md](https://github.com/CityOfLosAngeles/mobility-data-specification/blob/master/README.md)~~, [provider/README.md](https://github.com/CityOfLosAngeles/mobility-data-specification/blob/master/provider/README.md), and [agency/README.md](https://github.com/CityOfLosAngeles/mobility-data-specification/blob/master/agency/README.md)~~.

(2) Have the Latest Release link in the [Versions](https://github.com/CityOfLosAngeles/mobility-data-specification#versions) section point to the latest tag (e.g. [0.3.1](https://github.com/CityOfLosAngeles/mobility-data-specification/tree/0.3.1)) instead of [master](https://github.com/CityOfLosAngeles/mobility-data-specification/tree/master) to get a nice URL with version number.

~~(2) Add links to previous release versions on the [provider/README.md](https://github.com/CityOfLosAngeles/mobility-data-specification/blob/master/provider/README.md) and [agency/README.md](https://github.com/CityOfLosAngeles/mobility-data-specification/blob/master/agency/README.md)~~

~~(3) Change the github default branch to be that of the release with the latest release version (would this currently be `master`?). This way (1) will always reflect the latest release version of MDS. The dev branch could be versioned with the next intended release.~~

### Is this a breaking change
* [ ] Yes, breaking
* [X] No, not breaking
* [ ] I'm not sure

### `Provider` or `agency`

For which API is this feature being requested:

* [ ] `provider`
* [ ] `agency`
* [X] both

### Describe alternatives you've considered

Do nothing and let everyone learn to navigate github tags ~~versions~~ to jump back in time.

**Comment by thekaveman** [comment]
The workflow you describe for navigating to a particular version is made much easier by using the `tags` drop-down:

![image](https://user-images.githubusercontent.com/1783439/58139651-8679af80-7bf0-11e9-89cc-e8766b570169.png)

The selected tag/version also shows up in the URL, e.g. https://github.com/CityOfLosAngeles/mobility-data-specification/tree/0.2.1.

Does maintaining the version number in another place (in addition to tags, releases, branches, and the JSON schema files) provide all that much benefit over what is already natively in the GitHub interface? At some point, you have to use what the tool provides, right?

There have been numerous discussions here and on the phone calls regarding the branching structure, `master` representing the most recent release, `dev` representing the next upcoming release (and being default because all PRs target the default branch, by default), etc. I'm not inclined to think that will be changing again soon, but open to more input.

**Comment by craastad** [comment]
Good points. The github tags significantly improves navigation. The version in the URL removes the need for versioning in the provider and agency READMEs.

The only remaining issue is landing on the github page, clicking [Latest Release](https://github.com/CityOfLosAngeles/mobility-data-specification/tree/master) in the [Versions section](https://github.com/CityOfLosAngeles/mobility-data-specification#versions) and going to master with no clear version in the URL path. Could we redirect this explicitly to the latest tag (i.e. 0.3.1)? And/or add versioning in the main README somewhere?

I've updated the original issue with these.

**Comment by hunterowens** [comment]
I think the last idea here would be to change the default version from `dev` -> `master`, I'm okay with this change assuming we limit the number of people who can merge PRs, since we will have to make sure that nobody merges into master which a lot of PRs will be opened against because that is the default branch. adding to the `future` milestone but leaving open.

**Comment by schnuerle** [comment]
Have we now resolved all these issues?
1. Main is now the default branch when you hit the MDS repo
1. There is [release info with links](https://github.com/openmobilityfoundation/mobility-data-specification/tree/dev#versions) on the main readme
1. Describe the versions on the [Wiki](https://github.com/openmobilityfoundation/mobility-data-specification/wiki)
1. Describe the versions on the [Releases page](https://github.com/openmobilityfoundation/mobility-data-specification/releases)

In the versions section, do we need to enumerate the versions and link to each of them via tags? [GBFS does this](https://github.com/NABSA/gbfs#read-the-spec--version-history). Would this solve your remaining concerns?
