### ISSUE TITLE
Harmonizing provider and agency api?

### ISSUE THREAD

**Issue by patata3000** [openmobilityfoundation/mobility-data-specification#345]
Do you plan to harmonize agency and provider APIs?
For example, we have accuracy in `/trips` and not in `/telemetry`. But we have satellites in `/telemetry` which is probably related.

Would you consider adding an example section describing how to use the APIs?
For example, when a provider starts working with an agency, what would be the steps for him and the agency to start working together. It would help understand the ideas why each part of the APIs exist.

**Comment by karcass** [comment]
Yes, one of the main efforts in 0.4.0 is to resolve many of the discrepancies between Agency and Provider.
`/telemetry` has `hdop` (horizontal dilution of precision), which is a field that is present in GPGGA and GPRMC sentences from most GPS chipsets.

**Comment by patata3000** [comment]
Do you plan to do something about the format as well ? One is a list of geojson (provider) and the other is a list of gps json objects (agency). One is about trips (provider), the other one is not about trips (agency)

**Comment by karcass** [comment]
Agency is a superset of Provider, so the two specifications have somewhat different requirements.  Agency captures all data required to construct trips, so I'm not sure how you reached the conclusion that it's "not about trips".  

GeoJSON is a suitable format for a single vehicle trip, but not for collecting bulk telemetry across (potentially) multiple vehicles in a single POST.

**Comment by patata3000** [comment]
Yes "not about trips" was not clear sorry. What I mean is that we get trips annotated data from `provider` and not from `agency`. I understand that we can annotate ourselves the telemetries with the `/events` endpoint which is very fine to me. My problem is why don't we have the same format in `provider`? i.e. an `/event` and a `/telemetry` endpoint.
There is probably a good reason but I don't see it :/ . I'm asking this because it feels harder to understand 2 different formats and merge them than to have 1 format from the start.

**Comment by yoimnik** [comment]
related event: https://github.com/CityOfLosAngeles/mobility-data-specification/issues/271

**Comment by hunterowens** [comment]
moving to future.

**Comment by HenriJ** [comment]
I'll close this one as @TonioGarcia07 will follow up with #271 and list all inconsistencies between provider & agency
