### ISSUE TITLE
Dummy provider endpoint

### ISSUE THREAD

**Issue by patata3000** [openmobilityfoundation/mobility-data-specification#351]
Is there any dummy provider endpoint? I'd like to test an implementation from the agency side

**Comment by karcass** [comment]
@patata3000 not quite following the question.  Can you provide more specific details?

**Comment by patata3000** [comment]
Well I'm developing a consumer on the provider api. I was just wondering if there is an endpoint with fake data where I could test it. I don't need it anymore though but this may be helpful to some others.
I could ask the same question for the agency api as well. :)

**Comment by thekaveman** [comment]
Not an API endpoint per se, but [mds-provider-services](https://github.com/CityofSantaMonica/mds-provider-services) has tooling for [generating fake Provider data](https://github.com/CityofSantaMonica/mds-provider-services/tree/master/fake).

**Comment by hunterowens** [comment]
I think this might relate to the reference implementation that @jfh01 has talked about. Tagging him for more insight.

**Comment by schnuerle** [comment]
The solution mentioned by @thekaveman contains the only open source option I know of for generating fake MDS data for testing. 

Definitely a need for this, but not sure how much of a need or who would develop and maintain the code for each release. 

The mds-core reference implementation doesn't contain fake MDS data and needs active MDS endpoints to work.
