### ISSUE TITLE
Clarification of scope of status changes re: warehouses

### ISSUE THREAD

**Issue by rgangopadhya** [openmobilityfoundation/mobility-data-specification#373]
### Is your feature request related to a problem? Please describe.

There is some ambiguity in the spec about what the scope of the status changes endpoint is. From [the spec](https://github.com/CityOfLosAngeles/mobility-data-specification/blob/dev/provider/README.md#status-changes):

> The status of the inventory of vehicles available for customer use.

It is not rare for providers to include devices that are in one of their warehouses in the status changes endpoint, which adds noise that all consumers of this endpoint need to deal with individually.

### Describe the solution you'd like

 I think it is worth clarifying what exactly we mean by "available for customer use" in the spec. For example a device that is in a warehouse doesn't count as "available for customer use," but the language could be clearer about that.

### Is this a breaking change

 * No, not breaking

### `Provider` or `agency`

For which API is this feature being requested:

 * `provider`

**Comment by hunterowens** [comment]
I think is is probably fine to add to docs. @rgangopadhya do you have an PR that you can add?

**Comment by hunterowens** [comment]
not blocking for 0.4.0 vs 0.4.1, so changing milestone given release schedule

**Comment by thekaveman** [comment]
@rgangopadhya this hasn't seen any recent activity - still something you are interested in working on for an upcoming release?

**Comment by thekaveman** [comment]
Continuing to punt this as we haven't heard anything in a while.

**Comment by schnuerle** [comment]
I think we have this covered with the `removed` state now. Will reopen if you disagree. https://github.com/openmobilityfoundation/mobility-data-specification/blob/main/general-information.md#vehicle-states
