### ISSUE TITLE
Moving MDS from the City of Los Angeles to the Open Mobility Foundation

### ISSUE THREAD

**Issue by jfh01** [openmobilityfoundation/mobility-data-specification#386]
Hi, I’m Jascha Franklin-Hodge, the Executive Director of the Open Mobility Foundation.

In the next few weeks, ownership of the `mobility-data-specification` repository, along with `mds-core` and `mds-compliance-mobile` will be [transferred](https://help.github.com/en/articles/transferring-a-repository) from the @CityOfLosAngeles organization on GitHub to the @openmobilityfoundation organization. This reflects the donation of the MDS codebase to the Open Mobility Foundation by the City of Los Angeles. The transfer will take place after the release of MDS 0.4.0.

The success of MDS has only been possible through the engagement and contributions of the MDS community. OMF and LADOT want to build on this great work, and bring the community along as the OMF takes on the role of shepherding future development. By moving the MDS codebase from LADOT to OMF, we aim to allow the existing MDS community to continue to thrive while providing new, multistakeholder governance that allows this work to grow as a true open source project. You can read more about the Open Mobility Foundation here: [http://www.openmobilityfoundation.org/](http://www.openmobilityfoundation.org/).

Below are some details about how this code transfer will work. **Please respond to this issue with feedback, suggestions, and questions.** You can also email jascha@openmobilityfoundation.org.

---

**_Technical considerations_**
When the repositories move, all existing history and work-in-progress will transfer over. GitHub will automatically redirect links and forks based on the old repository location. However, GitHub recommends updating any local clones to point to the new repository URL. See [here](https://help.github.com/en/articles/transferring-a-repository) for details.

Some issue and PR assignments may disappear as part of the repository transfer. Assignments are not widely used in the current repositories, so we do not anticipate any significant impacts.

**_Process considerations_**
Contributor license agreement: All are welcome to contribute to MDS after it has moved into the Open Mobility Foundation. As is typical of any open source foundation, contributors must agree to the OMF’s [Individual Contributor License Agreement](http://members.openmobilityfoundation.org/wp-content/uploads/2019/06/Individual-CLA.pdf) (CLA) and [Participation Policies](https://members.openmobilityfoundation.org/wp-content/uploads/2019/06/OMFParticipationPolicies.pdf). People contributing on behalf of their employer will need to have their employer sign an [Entity Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLSd_fgjHawbSarWC4AlaLbMGHhfcUky7nX0-cfusaqglVQupcw/viewform) as well (OMF member organizations have already signed this as part of their membership). 

We are using CLA Assistant. The first time you submit a pull request to the OMF, you will receive an automated notification with a link to sign the CLA. 

The Contributor License Agreements and Participation Policies also apply to other forms of participation within OMF, including GitHub issues/comments, as well as remote or in-person conferences and events.  

_Communication_: The mds-announce email list will continue to be the forum for major announcements about MDS (new versions, events, meetings, etc.). It will, however, move to a [new home](https://groups.google.com/a/groups.openmobilityfoundation.org/forum/#!forum/mds-announce) within the groups.openmobilityfoundation.org domain. All existing subscribers will be moved over.

_MDS provider release process_: The current MDS provider release process will largely transfer over into the new Provider Services Working Group established under the Open Mobility Foundation. Hunter Owens (@hunterowens) will chair this working group. Working group planning will take place on the [mds-provider-services](https://groups.google.com/a/groups.openmobilityfoundation.org/forum/#!forum/mds-provider-services) mailing list. Meetings will be announced on mds-provider-services and the main [mds-announce](https://groups.google.com/a/groups.openmobilityfoundation.org/forum/#!forum/mds-announce) mailing list.

_MDS city services / agency release process_: We are in the process of establishing a development and release process for the MDS agency API and reference implementation (mds-core repository). This will be overseen by the City Services Working Group in OMF. The working group will be chaired by Henri Jouhad (@henrij). Working group planning and discussion happen on the [mds-city-services](https://groups.google.com/a/groups.openmobilityfoundation.org/forum/#!forum/mds-city-services) mailing list. Meetings will be announced on mds-city-services and the main [mds-announce](https://groups.google.com/a/groups.openmobilityfoundation.org/forum/#!forum/mds-announce) mailing list.

**_Legal considerations_**
As the City of Los Angeles contributes code to the Open Mobility Foundation, it is the intent of both parties to preserve the validity of existing permits, laws, or municipal code that reference MDS. Previously released versions of MDS will continue to exist, unchanged, within the OMF’s GitHub structure. Links to the transferred repositories in the @CityOfLosAngeles GitHub organization will automatically redirect to @openmobilityfoundation. The City of Los Angeles will memorialize the code contribution in a letter that will be linked to from the GitHub repo.

In the OMF, source code will be subject to the Apache License v2.0. Documentation and non-code contributions will be licensed under Creative Commons CC-BY v4.0.

**_Next steps / target dates_**
**By 10/23/2019:** Collect feedback (please respond on this GitHub issue).
**By 10/25/2019:** Create a pull request that will reflect proposed changes to process in README, CONTRIBUTING, LICENSE, and other documentation.
**11/01/2019:** Merge documentation update pull request and complete repository transfer

**_Long-term direction_**
The Open Mobility Foundation’s [bylaws](https://members.openmobilityfoundation.org/wp-content/uploads/2019/08/OMF-Bylaws-CURRENT-1.pdf) anticipate the creation of an Architectural Landscape document that outlines the foundation’s approach to technology architecture and lays out a roadmap for planned deliverables. This will, in conjunction with the input of OMF’s working groups and contributors, shape the direction of MDS and other future outputs of OMF.

The [Transitional Landscape Architecture](http://www.openmobilityfoundation.org/wp-content/uploads/2019/10/OMF-Transitional-Architectural-Landscape-FINAL.pdf), adopted by the OMF Board of Directors, is intended to serve as an initial set of guideposts for ongoing development of MDS while a more complete document is created.

**Comment by jfh01** [comment]
This issue has been edited to reflect a revised mailing list structure. This will be fully documented in README.md once the code transfer is complete.

**Comment by jfh01** [comment]
As part of the code transfer, OMF intends to relicense the mobility-data-specification repository under the CC-BY 4.0 license. This is reflected in #390.

**Comment by hunterowens** [comment]
Move done! @jfh01 to setup CLA assistant and then close this issue!

**Comment by hunterowens** [comment]
CLA assistant is up. Closing!
