### ISSUE TITLE
Add `parking_verification_url` as a status_change field

### ISSUE THREAD

**Issue by billdirks** [openmobilityfoundation/mobility-data-specification#407]
### Is your feature request related to a problem? Please describe.

One use of parking photos is to verify that vehicles are not blocking the PROW in near realtime. If a vehicle is determined to be blocking the PROW then it can be cleaned up.

### Describe the solution you'd like

Currently parking photos are returned in the `/trips` endpoint in the `parking_verification_url` field. However, `/trips` is a historical endpoint and may not be populated until well after the vehicle has been blocking the PROW. The new `/events` endpoint is near-ish realtime and seems like the appropriate place to put this since parking is associated with a status change event that ends a trip.

### Is this a breaking change

A breaking change would require consumers or implementors of the API to modify their code for it to continue to function (ex: renaming of a required field or the change in data type of an existing field). A non-breaking change would allow existing code to continue to function (ex: addition of an optional field or the creation of a new optional endpoint). 

 * No, not breaking

This should be an optional field and is not a breaking change. If we also want to remove the photo url from the trips endpoint, that would be breaking. We could do that as a separate change.

### Impacted Spec

For which spec is this feature being requested?

 * `provider`

### Describe alternatives you've considered

The alternative is to join the data for trips and status_changes. This is doable, but the guarantees for timeliness aren't as strong.

### Additional context

If this is something we decide to move forward on, I can write up a PR that includes updating the specification wording and the json schema changes.

**Comment by schnuerle** [comment]
Hi @billdirks is this still a feature you'd like to see, and do you have some organizations asking for it? If so we may be able to put it in the 1.2 release since it's minor.

**Comment by billdirks** [comment]
@schnuerle We still think this is a good change but not one we're actively advocating. I don't know of any organizations that are pressing for this.

**Comment by quicklywilliam** [comment]
@marie-x I am curious if you know of any Agency agencies who are using parking photos for policy enforcement? If it is going to go in status it seems like it should also go into events…

**Comment by marie-x** [comment]
@quicklywilliam not that I know of

**Comment by schnuerle** [comment]
I feel like the inclusion of this in certain endpoints is improved with #796, is that correct?

**Comment by marie-x** [comment]
It's in all events now, both Agency and Provider, as optional.

**Comment by schnuerle** [comment]
Added for both Agency and Provider in the [trip attributes](https://github.com/openmobilityfoundation/mobility-data-specification/blob/dev/data-types.md#trip-attributes) object for MDS 2.0.
