### ISSUE TITLE
Extend vehicle type definitions to improve ability to report on equity, access, and safety

### ISSUE THREAD

**Issue by jfh01** [openmobilityfoundation/mobility-data-specification#426]
In conversations with various folks working on defining metrics for equity, accessibility, and safety, the need for data about vehicle form factor and other characteristics has been raised. For example:

- Passenger capacity determines if a vehicle could be used to transport kids
- Cargo capacity has implications for utility of vehicle for shopping or other errands
- Number of wheels has impacts utility of vehicle to people with mobility limitations or who may not be comfortable with less stable vehicles
- Standing versus seated can impact who can comfortable use a vehicle
- Understanding vehicle safety features (helmets, signals, sidewalk riding detection, speed limiters, etc.) in the context of crashes/injuries may improve understanding of regulators and researchers

[SAE J3194](https://saemobilus.sae.org/content/J3194_201911/) defines a taxonomy which address some of these vehicle characteristics.

Could/should we add data points like these into MDS? This could take the form of additional flags/fields in the `agency` `vehicle` endpoint and the `provider` `trips` endpoint. Alternatively, it may make sense to define a `vehicle_model_id` field which maps to a separate table where individual characteristics are defined.

This issue was also touched on in discussion of #416.

**Comment by karcass** [comment]
I used to work at Zipcar, and we had a vehicle database with many of these attributes.  Including this information seemed like overkill for micromobility, but is clearly useful in many other mobility contexts.  I would be interested in participating in putting together a proposal for the 0.5.0 timeframe.

**Comment by jfh01** [comment]
That would be great if you could take this on for 0.5.0. 

As an example of relevance for micromobility, there is a substantial gender disparity. One potential factor for this is that micromobility vehicles generally do not accommodate trips related to childcare or household errands (which are still disproportionally fall to women). New form factors are emerging that may make these vehicles more useful for these kinds of trips and it would be helpful to be able to track where they are available and how they’re used.

**Comment by jiffyclub** [comment]
In addition to reporting, being able to specify accessible vehicle types would help with policies that mandate certain levels of fleets be accessible vehicles. See some reporting on such vehicles being used in San Francisco here: https://www.masstransitmag.com/alt-mobility/shared-mobility/bicycle-scooter-sharing/press-release/21237270/san-francisco-municipal-transportation-agency-sfmta-sfmta-rolling-out-adaptive-scooters

**Comment by joshuaandrewjohnson1** [comment]
@jiffyclub can you clarify if the intention was to use this in any reporting as you mentioned in your comment, or only in the Policy API? Just want to flag the privacy risk if the intention was for reporting purposes (the reason for the [Reports API](https://github.com/openmobilityfoundation/mobility-data-specification/blob/main/provider/README.md#reports)).

**Comment by jiffyclub** [comment]
I meant that an `adaptive_scooter` vehicle type or some other vehicle type metadata would be necessary for a city to create an MDS policy mandating a certain number or percentage of such vehicles.

**Comment by schnuerle** [comment]
We've added a lot of these options and new fields as part of MDS 2.0, and can add more in the future if needed for specific use cases.
