### ISSUE TITLE
Modify /trips to represent docked start/end locations

### ISSUE THREAD

**Issue by thekaveman** [openmobilityfoundation/mobility-data-specification#428]
### Is your feature request related to a problem? Please describe.

This Issue follows from the [Provider WG discussion on 2020/01/16](https://github.com/openmobilityfoundation/mobility-data-specification/wiki/Web-conference-notes,-2020.01.16-(Provider-Services-wg)) and the existing Issue #374 and related PR #427 related to bringing docked bikeshare support to MDS Provider.

### Describe the solution you'd like

The current `/trips` endpoint was envisioned with dockless micromobility in mind - specifically, trips have a geographic (lat/lng) start and end location. In the world of docked bikeshare/micromobility, we would rather represent the trip as starting/ending at a particular dock/stop.

### Is this a breaking change

* Yes, breaking

Likely breaking as we would be changing the `/trips` definition.

### Impacted Spec

* `provider`

### Describe alternatives you've considered

We want MDS to represent docked bikeshare true to the spirit of MDS - granular data useful in regulatory and planning contexts. While possible, simply encoding GBFS data into MDS endpoints/data types wouldn't represent a true evolution of the MDS spec.

**Comment by jfh01** [comment]
Since start / end are represented via the `Route`, could we use define a GeoJSON "[foreign member](https://tools.ietf.org/html/rfc7946#section-6.1)" to include in the `Feature` for the start/end point of the `Route`.

**Comment by schnuerle** [comment]
I believe #442 will resolve this issue, adding the stop_id as an optional parameter.

**Comment by schnuerle** [comment]
This is sussed with #442.  Thanks @avatarneil and @thekaveman.
