### ISSUE TITLE
Revise state machine diagram to address new status and event types

### ISSUE THREAD

**Issue by jfh01** [openmobilityfoundation/mobility-data-specification#431]
PRs #429 and #275 will add additional status and/or event types to the `agency` API. We will need to update the state machine diagram in [agency/README.md](https://github.com/openmobilityfoundation/mobility-data-specification/blob/dev/agency/README.md) to reflect any changes that are merged. Actual diagram is located [here](https://github.com/openmobilityfoundation/mobility-data-specification/blob/dev/agency/images/MDS_agency_event_state.png)

**Comment by jfh01** [comment]
@karcass @whereissean Can you guys include the original, editable doc from which the PNG was generated in the `images` folder? That will make it easier for others to update in the future.

**Comment by karcass** [comment]
We don't have it, our commercial illustrator does.

I would prefer that we wait on the other PR that will land in 0.4.1 for the auto-generator.

**Comment by jfh01** [comment]
Ah, right. We went through that one quickly today and I missed the substance of it. Closing this out.
