### ISSUE TITLE
Policy: inconsistent types for timestamps (string vs. number)

### ISSUE THREAD

**Issue by ascherkus** [openmobilityfoundation/mobility-data-specification#432]
**Describe the bug**
The examples contained in the policy README.md have all timestamps declared as strings, but the examples.md uses numbers.

**To Reproduce**
Steps to reproduce the behavior: N/A

**Expected behavior**
I believe for consistency across the MDS specification that timestamps are milliseconds represented as numbers.

**Additional context**
Came across this while prototyping a tool for #423.

Happy to send out a PR - just want clarification before doing so!

**Comment by karcass** [comment]
Yes, we should be consistent.  Good catch @ascherkus.  Please send a PR while I look at the other two issues you filed.  :)

**Comment by ascherkus** [comment]
Will take a crack!

**Comment by schnuerle** [comment]
This issue is closed with PR #523.
