### ISSUE TITLE
Modify /status_changes to represent docked event locations

### ISSUE THREAD

**Issue by thekaveman** [openmobilityfoundation/mobility-data-specification#438]
### Is your feature request related to a problem? Please describe.

This Issue follows from the Provider WG discussions on [2020/01/16](https://github.com/openmobilityfoundation/mobility-data-specification/wiki/Web-conference-notes,-2020.01.16-(Provider-Services-wg)) and [2020/01/30](https://github.com/openmobilityfoundation/mobility-data-specification/wiki/Web-conference-notes,-2020.01.30-(Provider-Services-wg)) and the existing Issues #374 and #428 and related PR #427 related to bringing docked bikeshare support to MDS Provider.

### Describe the solution you'd like

The current `/status_changes` endpoint (and by extension, the `/events` endpoint which inherits the data schema) was envisioned with dockless micromobility in mind - specifically, events have a geographic (lat/lng) location. In the world of docked bikeshare/micromobility, we would rather represent an event as occurring at a particular dock/stop.

### Is this a breaking change

* Yes, breaking

Likely breaking as we would be changing the `/status_changes` definition.

### Impacted Spec

* `provider`

### Describe alternatives you've considered

We want MDS to represent docked bikeshare true to the spirit of MDS - granular data useful in regulatory and planning contexts. While possible, simply encoding GBFS data into MDS endpoints/data types wouldn't represent a true evolution of the MDS spec.

**Comment by schnuerle** [comment]
Confirming that #427 will resolve this issue @thekaveman.

**Comment by schnuerle** [comment]
We've got this resolved with #427.
