### ISSUE TITLE
rule_id is in some examples but not in specification

### ISSUE THREAD

**Issue by Glutamat42** [openmobilityfoundation/mobility-data-specification#445]
**Describe the bug**
Some rules in the policy examples have a rule_id but the policy/REAMDE.md does not list this attribute.
It was added to the README file in the second commit, but removed again one commit after.

**To Reproduce**
Steps to reproduce the behavior: N/A

**Expected behavior**
I would either expect it
1. not beeing in examples
2. listed as optional parameter
3. listed as required parameter and beeing in all examples

I would prefer (3) to be consistent with policy (required policy_id) and geography (also required id) and beeing able to uniquely identify a rule by its id

**Comment by antoinewg** [comment]
Already have a PR here https://github.com/openmobilityfoundation/mobility-data-specification/pull/409 but I can't merge it
