### ISSUE TITLE
Policy spec doesn't state whether or not clients should specify an MDS version through the Accept header

### ISSUE THREAD

**Issue by jrheard** [openmobilityfoundation/mobility-data-specification#447]
### Describe the problem

According to https://github.com/openmobilityfoundation/mobility-data-specification/tree/dev/policy#rest-endpoints ,

> Responses must set the Content-Type header, as specified in the [Provider versioning](https://github.com/openmobilityfoundation/mobility-data-specification/blob/dev/provider/README.md#versioning) section.

This seems pretty clear: I take it to mean that responses to requests for Policy endpoints must include a `Content-Type` header that indicates the version of MDS associated with the response.

What's not clear to me is: does the **rest** of the Provider spec's versioning section's behavior need to be implemented as well for Policy endpoints, or is this responses-must-set-a-`Content-Type`-header portion the **only** http-header-related behavior that's required in Policy-land?

---

Specifically, I'm curious about whether or not the Policy endpoints should implement these versioning-related behaviors described in the Provider spec:
* "Clients must specify the version they are targeting through the Accept header."
* "If an unsupported or invalid version is requested, the API must respond with a status of `406 Not Acceptable`."
* "A client negotiates available versions using the `OPTIONS` method to an MDS endpoint."

---

Also, the Provider spec's versioning section includes this line:

> Since versioning was not added until the 0.3.0 release, if the Content-Type header is not set as specified above, version 0.2 must be assumed.

Does some form of this line (presumably with a different default version number) apply to the Policy spec?

### Describe the solution you'd like

I think that the Policy spec should be modified to answer these questions.

If the `Content-Type` response header is the **only** versioning-header-related behavior required by the Policy spec, then the spec should be modified to explicitly say so.

If the Policy endpoints must implement the full set of behaviors described in https://github.com/openmobilityfoundation/mobility-data-specification/blob/dev/provider/README.md#versioning , then the spec should say so, and should be clear about any Policy-specific changes that might be necessary (eg using 0.4 as the default MDS version instead of 0.2, etc).

### Is this a breaking change

A breaking change would require consumers or implementors of the API to modify their code for it to continue to function (ex: renaming of a required field or the change in data type of an existing field). A non-breaking change would allow existing code to continue to function (ex: addition of an optional field or the creation of a new optional endpoint). 

* I'm not sure

### Impacted Spec

For which spec is this feature being requested?

 * `policy`

**Comment by Retzoh** [comment]
Hi, this is something I have already started tracking in #422.
We discussed the issue in the last city-services call. The consensus was on moving the `Versioning` section from the Provider spec into a separate file, and link it from the various APIs. How do you feel about this?

I plan on proposing a PR this week for this, to discuss the exact details of the issues you are raising here.

**Comment by jrheard** [comment]
Perfect! Moving the `Versioning` section into a separate file that's linked to from all of the different APIs seems like absolutely the correct approach here. Thank you!

**Comment by Retzoh** [comment]
@jrheard fyi #444 has been merged, solving this.
