### ISSUE TITLE
Provide guidance on how to chose which MDS APIs to implement / use

### ISSUE THREAD

**Issue by jfh01** [openmobilityfoundation/mobility-data-specification#451]
The OMF frequently gets questions about which APIs an organization should use/implement, especially in the choice between agency and provider. This issues is to discuss new documentation in the wiki which helps explain the different APIs and which might be appropriate for a given user.

Document here:

https://github.com/openmobilityfoundation/mobility-data-specification/wiki/Understanding-MDS-APIs

This was originally a PR (#448), but a decision has been make to post this document in the wiki rather than in the repository.  Any further discussion and feedback should take place here. The plan is to make this official (and link to it from the README) as part of 0.4.1.

---

Since this Issue is meant more for ongoing discussion, and since #452 was merged for `0.4.1`, removing this from the `0.4.1` milestone.

**Comment by toddapetersen** [comment]
Is this still open for edits?

**Comment by thekaveman** [comment]
Since this Issue is meant more for ongoing discussion, and since we merged #452 for 0.4.1, I'm removing this from the 0.4.1 milestone and marking with a new label for `discussion` items.

**Comment by jfh01** [comment]
Removed draft header from wiki page. Considering this "published"
