### ISSUE TITLE
Use a generic versioning header

### ISSUE THREAD

**Issue by Retzoh** [openmobilityfoundation/mobility-data-specification#455]
### Is your feature request related to a problem? Please describe.

In #444 we moved the versioning spec to one file, used by all the APIs.
To avoid breaking changes in the Provider API, the `Accept-content` header was kept as `application/vnd.mds.provider+json`.

### Describe the solution you'd like

With the 0.5.0 milestone, we can remove the `.provider` part of the header since it is now available for all the APIs.

The header would become `application/vnd.mds+json`.

### Is this a breaking change

A breaking change would require consumers or implementors of the API to modify their code for it to continue to function (ex: renaming of a required field or the change in data type of an existing field). A non-breaking change would allow existing code to continue to function (ex: addition of an optional field or the creation of a new optional endpoint). 

 * Yes, breaking

### Impacted Spec

For which spec is this feature being requested?

 * `agency`
 * `policy`
 * `provider`

### Describe alternatives you've considered

Leave the header as it is.

### Additional context

None

**Comment by karcass** [comment]
Sounds good to me

**Comment by schnuerle** [comment]
It looks like this change is now in `dev`, correct @Retzoh @karcass?  Can we close this issue now?

**Comment by karcass** [comment]
I believe so.

**Comment by thekaveman** [comment]
[Yes it is in there](https://github.com/openmobilityfoundation/mobility-data-specification/blob/dev/general-information.md#versioning).

Closing.
