### ISSUE TITLE
Review Release Candidate 0.4.1

### ISSUE THREAD

**Issue by thekaveman** [openmobilityfoundation/mobility-data-specification#459]
### Summary

The Release Candidate for MDS `0.4.1` has been submitted: https://github.com/openmobilityfoundation/mobility-data-specification/releases/tag/0.4.1-rc1

Please use this issue to track Technology Council and OMF Board feedback and/or requested changes.

### Action Item

Please close this Issue upon OMF Board Approval to indicate that the Release Candidate may be made official.

**Comment by jfh01** [comment]
We are currently scheduling a review by the tech council. I will update the [wiki](https://github.com/openmobilityfoundation/mobility-data-specification/wiki) as the schedule unfolds.

**Comment by thekaveman** [comment]
In conversation with the Technology Council, it was decided to adjust the language around required/optional endpoints to instead more clearly articulate that some endpoints are "beta" and may see further refinement both in the endpoint definitions and in their implementations.

#468 introduces this change to the 0.4.1 Release Candidate

**Comment by jfh01** [comment]
The Technology Council is currently voting to on whether or not to send their recommendation re: 0.4.1 to the Board of Directors. I currently expect a board vote on or around 5/8/2020.

**Comment by jfh01** [comment]
Based on a Board review / discussion, we have added PRs #478 and #479.

**Comment by jfh01** [comment]
Board is likely to vote on this at the 5/13 meeting.

**Comment by thekaveman** [comment]
Minor addition to the Provider docs to link to the `events` and `vehicles` JSON schemas under the relevant section: #490

**Comment by jfh01** [comment]
The Board has approved 0.4.1 at the 5/13 meeting. We will be updating GitHub shortly.

**Comment by thekaveman** [comment]
Closed by #495
