### ISSUE TITLE
Release Guidelines

### ISSUE THREAD

**Issue by thekaveman** [openmobilityfoundation/mobility-data-specification#460]
We've recently started building out this repository's Wiki in force, with ancillary "meta" documentation in addition to calendar/agendas/minutes for the Working Group calls. As the `ReleaseGuidelines.md` went through [another major set of changes with `0.4.1`](https://github.com/openmobilityfoundation/mobility-data-specification/pull/453), I'm wondering if maybe this document makes more sense as part of the Wiki than with the repository itself?

On one hand, documents within the main repo need to follow the lengthy release/review process and so changes can be hard to come by, particularly quick ones. On the other hand, maybe certain meta-documentation like the ReleaseGuidelines.md *should* go through this process? I'm on the fence but leaning towards this document moving to the Wiki.

Curious of other's thoughts, both on where the document lives and the [process itself](https://github.com/openmobilityfoundation/mobility-data-specification/blob/release-0.4.1/ReleaseGuidelines.md#preparing-a-release-candidate).

**Comment by jfh01** [comment]
As discussed on the wg-ops call today, release guidelines (and similar docs) probably need less formality than what we put into a release but more than what goes onto the wiki. As such, we're going to explore creating a separate repo for this sort of process and policy docs.

**Comment by sarob** [comment]
discussion is continuing here https://groups.google.com/a/openmobilityfoundation.org/forum/#!topic/wg-ops/V6AkubjlBh0

with proposed changes here https://docs.google.com/document/d/13NiJ7NxExo-e_8Z9G6U9V_2zNqMwA0zGBYJe1eVpUjU/edit?usp=sharing

11mar wg-ops meeting we will review this

**Comment by sarob** [comment]
reviewed in the 11mar wg-ops meeting. Comments and changes the gdoc inline. Additional review in the next 18mar wg-ops meeting

**Comment by schnuerle** [comment]
We are moving this document out of the MDS repo and into the Governance repo as of 1.0.0.  You can see the page here: https://github.com/openmobilityfoundation/mobility-data-specification/blob/release-1.0.0/ReleaseGuidelines.md

We are keeping this page around for a while to help with redirecting people who have links to it in the MDS repo.
