### ISSUE TITLE
Provide ability for providers to communicate system problems to regulatory agencies

### ISSUE THREAD

**Issue by cartograham** [openmobilityfoundation/mobility-data-specification#466]
As an MDS-consuming agency, it would be valuable to have the ability to query an endpoint that provides information about system problems with a provider's MDS feed or system in general.
Example problems could be:
* IOT/comms issues with overall system.
* IOT/comms issues with vehicle(s)
* Other problems that aren't vehicle-specific status changes, but overall system problems that are not easily conveyed in current feed.

### Is this a breaking change

 * No, not breaking

### Impacted Spec

Not sure.

 * `provider`

### Describe alternatives you've considered

Possibly, the GBFS endpoint 'system_alerts.json' could be used, but seems a bit hacky and not intended for communicating problems provider <---> agency, but rather to the public.

**Comment by schnuerle** [comment]
Moving to 1.1.0 since we are close to finalizing 1.0.0 and there is no PR/discussion for this yet.

**Comment by schnuerle** [comment]
Still seems like a good idea in general, though may be a breaking change and not good for 1.1.0. Does anyone else have thoughts on the utility of this and how to implement?

**Comment by schnuerle** [comment]
I think this will be addressed in #628 if we move forward on that. So adding a comment there and follow along with your thoughts and for updates.
