### ISSUE TITLE
Clarify meaning of "elsewhere"

### ISSUE THREAD

**Issue by karcass** [openmobilityfoundation/mobility-data-specification#471]
### Is your feature request related to a problem? Please describe.

During the Agency/Provider reconciliation WG meetings, several participants reported confusion about the definition of the "elsewhere" status in Agency.  After some explanation, the consensus was that (a) "elsewhere" made sense to include in both Agency and Provider, but (b) it needed clarification.

### Describe the solution you'd like

As part of reconciliation, I will make a PR to extract the status information from both Provider and Agency into a shared document (like we did with API versioning), and at that time clarifying working will be added.

### Is this a breaking change

 * No, not breaking in isolation (just adding clarity to definition)

### Impacted Spec

For which spec is this feature being requested?

 * `agency`
 * `policy`
 * `provider`

### Describe alternatives you've considered

The reconciliation WG considered dropping 'elsewhere' but consensus was in favor of retaining it.

### Additional context

Note at the moment

**Comment by karcass** [comment]
This will be included in the PR to address #271.  Here is the draft: https://github.com/lacuna-tech/mobility-data-specification/pull/7

**Comment by schnuerle** [comment]
Completed, thanks Max.
