### ISSUE TITLE
Provider: indicate municipality-wide service pause in Status Changes API

### ISSUE THREAD

**Issue by chloerevery** [openmobilityfoundation/mobility-data-specification#509]
### Is your feature request related to a problem? Please describe.

Occasionally providers must temporarily cease service, either at the direct request of the city or due to inclement weather. The [Provider Status Changes API specification](https://github.com/openmobilityfoundation/mobility-data-specification/tree/master/provider#status-changes) does not specify how the provider status change API should represent this state.

**When a vehicle status change occurs in the course of a temporary cessation in service, what `event_type_and_reason` should be associated with the status change?**

### Describe the solution you'd like

It seems like this use case fits well with the existing `removed` `event_type`, but it's unclear what the associated `reason` should be. Two possible solutions might be:

1. Reuse `removed / service_end` `event_type_and_reason` for this use case (current description for `service_end`, `"Device removed from street because service has ended for the day (if program does not operate 24/7)"`, would need to be updated).
2. Reuse `removed` `event_type` but introduce a new `reason` (`service_closure`?).

### Is this a breaking change

* No, not breaking

### Impacted Spec

For which spec is this feature being requested?

 * `provider`

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by quicklywilliam** [comment]
Thanks for filing this. I would advocated for the second solution here, a new `reason`. I could see it being useful to express Service Closures in the Policy API, and having an explicit `reason` would help assess and report on compliance.

**Comment by jfh01** [comment]
Thanks for submitting this. 

Would love to see this get into the 1.0.0 release as part of the provider/agency reconciliation work being done in #506.

**Comment by schnuerle** [comment]
We've now merged PR #506 to the dev branch, so we'll look at if this is resolved now, if it can be resolved easily, or if it needs to go to the next release.  Tagging @karcass @thekaveman.

**Comment by schnuerle** [comment]
Not sure if this is resolved yet or not. Will look into it as I prepare the 1.0.0 release candidate.

**Comment by schnuerle** [comment]
We are going to have to move this good suggestion to 1.1.0 since adding a new event type “service_closure” under "removed" would have ripple impacts on the repo at this point (docs, SMD, schema).

**Comment by thekaveman** [comment]
In #506 we added the `system_suspend` and `system_resume` to handle cases like weather closure or other temporary suspensions of service. Do these event types capture the use-cases outlined in this issue?

**Comment by schnuerle** [comment]
Hi @chloerevery we talked about this today. The consensus was that with #506 we've added `system_suspend` and `system_resume` and that it should address your use cases. Please let us know here if they do not, thanks.

**Comment by schnuerle** [comment]
Closing but let us know if you have any concerns or unresolved issues with this.
