### ISSUE TITLE
Remove the "beta" designation from Provider -> events

### ISSUE THREAD

**Issue by schnuerle** [openmobilityfoundation/mobility-data-specification#528]
### Is your feature request related to a problem? Please describe.

Remove the beta designation from [Provider, events](https://github.com/openmobilityfoundation/mobility-data-specification/tree/main/provider#events).

### Describe the solution you'd like

I think it's time to remove the beta designation, but would like to discuss it first.

### Is this a breaking change

A breaking change would require consumers or implementors of the API to modify their code for it to continue to function (ex: renaming of a required field or the change in data type of an existing field). A non-breaking change would allow existing code to continue to function (ex: addition of an optional field or the creation of a new optional endpoint). 

 * I'm not sure, maybe if it then means this endpoint has to be implemented.

### Impacted Spec

For which spec is this feature being requested?

 * `provider`

### Describe alternatives you've considered

Leave as beta for another release.

**Comment by Retzoh** [comment]
I agree it could be removed.

**Comment by thekaveman** [comment]
In working on the JSON Schema updates for Reconciliation, I realized that the [events schema](https://github.com/openmobilityfoundation/mobility-data-specification/blob/main/provider/dockless/events.json) omits many of the necessary `definitions` that are referenced later in the schema document. This was 100% my mistake when I [added events to the schema generator](#458). 

@schnuerle and I briefly discussed and concluded that we will fix this for 1.0.0 as events comes out of beta. We won't offer a patch release 0.4.2 to fix it in the previous line as the beta designation gives some flexibility for "gaps" in the design.

If you are needing a valid events schema for 0.4.x, please respond here and we can discuss

**Comment by schnuerle** [comment]
Removing the beta designation in #532.  JSON Schema updates will be handled with issue #526.

**Comment by schnuerle** [comment]
Completed, merged to dev.

**Comment by Retzoh** [comment]
We use it at BlueSystems, it works fine.
