### ISSUE TITLE
Add Stop image to Policy 

### ISSUE THREAD

**Issue by schnuerle** [openmobilityfoundation/mobility-data-specification#555]
### Is your feature request related to a problem? Please describe.

As parking locations are created or designated by cities, providers and riders need more context to use them properly.  This would add an optional image path URL to the Policy API for Stops.  

### Describe the solution you'd like

This photo or illustration created by the city would be sent along in the Policy API for providers' information and could be communicated visually to riders what a Stop looks like, aiding in parking.

### Is this a breaking change

 * No, not breaking

### Impacted Spec

For which spec is this feature being requested?

 * `policy`

### Describe alternatives you've considered

Something similar could be added to Stops in Agency or Provider, but it's not clear to me what that could be.

### Additional context

Note that Stops do not yet exist in Policy, so this would be included as part of the development of Issue #554.

**Comment by schnuerle** [comment]
We will be discussing this tomorrow at our Joint Working Group meeting, so attend if you are interested.  

https://github.com/openmobilityfoundation/mobility-data-specification/wiki/Web-conference-notes,-2020.09.17-(Joint-Working-Group-City-Services)

**Comment by schnuerle** [comment]
**From the WG call yesterday.**

Could be added as an optional field in Stops.
Should be an easy thing to add. 
Could just be added as part of #554.

**Comment by karcass** [comment]
What form(s) would it take?  URL?  Base-64 encoded with mime type?  Other?

**Comment by Retzoh** [comment]
I think an url is best, to avoid having to fetch hundreds of megabytes of data when you are just looking for the list of existing stops and their location.

**Comment by schnuerle** [comment]
I will make a PR for this since it's pretty straightforward and there seems to be agreement on it.

**Comment by schnuerle** [comment]
Added the optional image URL to this [branch](https://github.com/openmobilityfoundation/mobility-data-specification/blob/ms-stops/general-information.md#stops) and soon to be PR.
