### ISSUE TITLE
Add Clarifying Language for "Unknown" and "Unspecified" Values

### ISSUE THREAD

**Issue by schnuerle** [openmobilityfoundation/mobility-data-specification#564]
### Is your feature request related to a problem? Please describe.

As part of 1.0.0 reconciliation work, add language to help clarify limitations on the use of certain new values for vehicle states and event types.

Would add a new proposed section in MDS documentation that explains how and when to use some unique vehicle states, like unspecified and unknown. Will go right before the “Vehicle State Events” section.

### Describe the solution you'd like

Here is the draft of the language to be added.  Has been reviewed by OMF staff, Ben at Bird, Dirk at Spin, Max at E&A, and Kegan Maher.  To be reviewed by OMF Board soon.

> **Limitations on the Use of Certain Values**
> 
> MDS is intended to communicate the provider's best available information to regulators. However there may be legitimate circumstances where providers do not have definitive or current information about devices on the ground. MDS incorporates some values to convey these situations.  These vehicle state and event type values are to be used sparingly and temporarily, and are not meant for repeated or prolonged use. These values exist to create logical coherence within MDS about vehicles that are operating abnormally or are out of communication. Cities may add language to their Service Level Agreements (SLAs) that minimize the use of these values by providers. 
> 
> **Vehicle State: Unknown**
> 
> The `unknown` vehicle state means that the vehicle cannot be reliably placed into any of the other available states by the provider. This could be due to connectivity loss, GPS issues, missing vehicles, or other operational variances. It is expected that `unknown` will not be used frequently, and only for short periods of time. As vehicles regain connectivity or are located by providers they should have their state corrected.
> 
> **Event Type: Unspecified**
> 
> The `unspecified` event type state transition means that the vehicle has moved from one state to another for an unspecified or unknown reason. It is used when there are multiple possible event types between states, but the reason for the transition is not clear. It is expected that `unspecified` will not be used frequently, and only for short periods of time. When more accurate information becomes available to the provider, it should be updated in the MDS data where applicable.

### Is this a breaking change

 * No, not breaking

### Impacted Spec

None

### Describe alternatives you've considered

N/A

### Additional context

[Working doc](https://docs.google.com/document/d/1GsiqRbb7pRLvNS239gF0j9rRLEQJtrTO125vYaJ20b4/edit)

**Comment by jrheard** [comment]
> As vehicles regain connectivity or are located by providers they should have their state corrected.

> When more accurate information becomes available to the provider, it should be updated in the MDS data where applicable.

(I'm not very familiar with the Agency portion of MDS, so my comment below is written from a Provider point of view)

It seems to me that these lines could be interpreted in two ways:

1. Providers should issue _new_ status changes, _in addition to_ the previous unknown-or-unspecified status changes
2. Providers should update the previously-published unknown-or-unspecified status changes "in place" - i.e. they should modify the preexisting status changes without publishing new "correction" status changes

I think that we should choose one of these two approaches, and that the language above should be modified to explicitly require that approach.

**Comment by schnuerle** [comment]
Language clarified after community feedback and review and approval from the OMF Board. Changes captured with [this commit](https://github.com/openmobilityfoundation/mobility-data-specification/commit/9a92de6d310f9ac97cf8214aa45db3fb8c899232).
