### ISSUE TITLE
Add 'located' event_type from 'Unknown' for symmetry with 'missing' 

### ISSUE THREAD

**Issue by schnuerle** [openmobilityfoundation/mobility-data-specification#566]
### Is your feature request related to a problem? Please describe.

With the 1.0.0rc, devices can go into Unknown from any state with 'missing'.  And they can leave Unknown with 'comms_restored' and 'unspecified' to any state, and to some states with a few other event_types.  But there is not a clear way to designate a device was located after having gone missing.

### Describe the solution you'd like

Would like to add 'located' event_type just out of Unknown. I can update the docs and the state machine diagram.

### Is this a breaking change

 * No, not breaking

### Impacted Spec

 * `agency`
 * `policy`
 * `provider`

### Describe alternatives you've considered

Leave out 'located'.  Could be called 'found' but 'located' seems more precise/consistent with other language.  Eg lost and found, vs missing and located.

### Additional context

Note this could be left for the 1.1.0 release if there is not consensus now.

**Comment by karcass** [comment]
Yes please

**Comment by schnuerle** [comment]
I'd like some feedback on this from providers and other experts, like @dirkdk @joshuaandrewjohnson1 @karcass @bhandzo.  This seems like a good thing to add, but want to make sure that it makes sense to you.

**Comment by schnuerle** [comment]
For the state machine diagram, the language at the bottom would be updated from this:

> Unknown Events (not shown in diagram):
> - Any state can go to Unknown with event_type comms_lost, missing, unspecified
> - Unknown can go to any state with event_type comms_restored, unspecified 

To this (**emphasis** to addition in the new text):

> Unknown Events (not shown in diagram):
> - Any state can go to Unknown with event_type comms_lost, missing, unspecified
> - Unknown can go to any state with event_type comms_restored, **located**, unspecified

**Comment by dirkdk** [comment]
yes sounds good. Sometimes location might be transmitted but off so untraceable , or vehicle is unreachable (in house of private person). It makes sense to distinguish between `comms_restored` and `located`.

**Comment by schnuerle** [comment]
Thanks for the feedback here and via the working group mailing list and elsewhere.  PR #570 is complete and merged for the 1.0.0 release.
