### ISSUE TITLE
Support for multiple modes/services in MDS

### ISSUE THREAD

**Issue by pomgod** [openmobilityfoundation/mobility-data-specification#574]
### Is your feature request related to a problem? Please describe.
Currently, it is possible to define a couple of modes but that often does not adequately enough describe a service. For routeplanning for example it is important to know if a service is station-based, free-floating, back-to-one. For most modes, the route is completely flexible/free but other modes like PT is fixed or semi-fixed (fixed routes with the possibility of deviation at certain points).

### Describe the solution you'd like

Adding field which describe the mobility system better with mode-independent terminology.

### Is this a breaking change

 * No, not breaking

### Impacted Spec

For which spec is this feature being requested?
 * `provider`

### Describe alternatives you've considered

We've considered putting it in a file ourselves together with other info related to our inner working.

**Comment by schnuerle** [comment]
Thanks for the idea!  Can you describe what you'd like to see in some more detail?  Which endpoints, what could the field be called (mode?), and what values could it have?  Some examples would help too.

**Comment by schnuerle** [comment]
The City and Provider Working Group Steering Committees met last week for the [Midway Checkpoint](https://github.com/openmobilityfoundation/governance/blob/main/technical/ReleaseGuidelines.md#checkpoints) for the 1.2.0 proposed release. The Checkpoint let them review feature proposals, align current work to goals, and ensure the release features and work is on track.  

For this work, we have created a [new rubric](https://github.com/openmobilityfoundation/mobility-data-specification/wiki/MDS-Feature-Evaluation) to help guide the evaluation, looking at feature utility, stakeholder adoption, implementation simplicity, direction consensus, and work completed as part of the evaluation criteria. The outcomes and actions from these discussions are summarized here:

> Very good utility and adoption potential for this, as well as potential consensus on urgency and direction. Not sure of how much work is needed, how to implement, or how complex changes would be.
> 
> **Actions**: Create a “Community Group” (in the creation process by the OMF) to have the discussions needed, decide on a solution, and find stakeholders to commit.

**Comment by schnuerle** [comment]
This will likely be a larger discussion of how we can add new modes (not just new vehicles) into MDS and how these modes can be supported in the state machine, events, etc. 

You can follow and leave some thoughts here: https://github.com/openmobilityfoundation/mobility-data-specification/discussions/652

**Comment by schnuerle** [comment]
We will be doing the code changes needed for this in the [feature-modes](https://github.com/openmobilityfoundation/mobility-data-specification/tree/feature-modes) branch. A link to the PR to `dev` will be added here once it's created.

**Comment by schnuerle** [comment]
This work and draft is merged to dev for the 2.0 release.
