### ISSUE TITLE
Add optional geography_type field to Geography spec

### ISSUE THREAD

**Issue by karcass** [openmobilityfoundation/mobility-data-specification#580]
### Is your feature request related to a problem? Please describe.

Per 1.1 Working Group meetings, the idea of clarifying Geography objects via free-form types in an optional `geography_type` was raised as a useful non-breaking addition.

### Describe the solution you'd like

Add an optional string field to the Geography object definition

### Is this a breaking change

 * No, not breaking

### Impacted Spec

For which spec is this feature being requested?

 * `geography`

### Describe alternatives you've considered

We thought about not adding it ... another proposal was to add a list of geography_types when a geography could plausibly be more than one type of area, but so far nobody has identified clear and useful examples of this.

**Comment by schnuerle** [comment]
Added in #582
