### ISSUE TITLE
Authorization Consistency Across MDS

### ISSUE THREAD

**Issue by schnuerle** [openmobilityfoundation/mobility-data-specification#584]
### Is your feature request related to a problem? Please describe.

Currently each MDS API has its own descriptions of authorization methods and options.

Provider: [Entire Auth.md page with JWT recommended](https://github.com/openmobilityfoundation/mobility-data-specification/blob/main/provider/auth.md)

Agency: [Authorization section that requires JWT](https://github.com/openmobilityfoundation/mobility-data-specification/tree/main/agency#authorization)

Policy: [Authorization is not mentioned](https://github.com/openmobilityfoundation/mobility-data-specification/tree/main/policy)

Geography: [Authorization section and bearer token language with public option](https://github.com/openmobilityfoundation/mobility-data-specification/tree/feature-geography/geography#authorization)

General Information: [Authorization is not mentioned](https://github.com/openmobilityfoundation/mobility-data-specification/blob/main/general-information.md)

### Describe the solution you'd like

These disparate authorization descriptions should be consolidated across MDS and likely put into the General Information page with sections for JWT.  The content from Provider could be a starting point, with additional subsections around optional JWT auth, public feeds, etc.  Then each API can reference and link to the appropriate section consistently.

### Is this a breaking change

 * I'm not sure

### Impacted Spec

For which spec is this feature being requested?

 * `agency`
 * `policy`
 * `provider`

### Describe alternatives you've considered

N/A

### Additional context

This came up in a Working Group call on [Oct 7 2020](https://github.com/openmobilityfoundation/mobility-data-specification/wiki/Web-conference-notes,-2020.10.08-(Joint-Working-Group-Provider-Services)#minutes).

**Comment by janedotx** [comment]
I think this is a very good idea. Whenever we write this unified authentication information, we should also note that the current reference implementation makes certain assumptions about the claims in the JWT provided by clients to gate certain data (e.g. only certain clients are authorized to view unpublished policies).

**Comment by schnuerle** [comment]
See notes from the [WG call](https://github.com/openmobilityfoundation/mobility-data-specification/wiki/Web-conference-notes,-2021.01.14-(Joint-Working-Group)#agenda) this week. 

- Not complex to fix, but a bit tedious
- Max can volunteer to do PR at some point
- Docs and organizing, not breaking or not, not changing
- May identify areas for improvements along the way

**Comment by schnuerle** [comment]
As part of the #506 #644 #796 work, authorization across MDS will be more consistent and clear. 

Note to make sure as part of 2.0 work we also make sure Policy, Geography, and Jurisdiction is required to be public, as promised here: https://github.com/openmobilityfoundation/mobility-data-specification/blob/main/general-information.md#optional-authentication

**Comment by marie-x** [comment]
I've been meaning to work on this, based on extensive work on the Lacuna side that we're happy to share.

**Comment by schnuerle** [comment]
That would be great to share what you are thinking. Seems like it would align well with the Agency/Provider work.

**Comment by schnuerle** [comment]
Do you think this is resolved with #796 @marie-x ?

**Comment by marie-x** [comment]
I haven't done the writeup yet.  If we can get the reconciliation work done, then I can work on this.  Else defer I think.  Don't feel strongly either way.

**Comment by schnuerle** [comment]
Complete with #835. If you have any recommended changes, leave a comment here for future inclusion during release review process.
