### ISSUE TITLE
[Policy API] Update docs regarding disabling older policies

### ISSUE THREAD

**Issue by fractalf** [openmobilityfoundation/mobility-data-specification#596]
The documentation for the *policy api* is not clear on how exactly one would disable an old policy with a new one.

As was discussed on the email-list, there is a "hidden" rule/thought behind how this works:

> If I have Policy X, and in a week I’m going to update it to Y, I can publish Y today, with a start_date a week from today, and have its prev_policies be the list [X].  Publishing Y does not deprecate X until Y takes effect.

This last part is not obvious from the docs: "*Publishing Y does not deprecate X until Y takes effect*". Please put some of this in the official docs.

**But**, there is one scenario which still is a bit unclear. Lets say Policy Y (which will deprecate Policy X in a week from now) was a mistake and instead you wanted it to be active **two weeks** from now. Since you can't delete it, you would publish Policy Z with a **start_date** two weeks from now and put Policy Y in **prev_policies**. However, by the rule defined earlier, this will not take affect before Policy Y is actually made active (and thereby disabling Policy X), since Policy Y has a **start_date** one week earlier than it's replacement Policy Z. So the mistake will be actually be active a whole week **before** it is disabled by Policy Z.

Thank you

**Comment by karcass** [comment]
I will make a PR with the new verbiage.  Thanks!

For the second issue -- changing only the `start_date` of a Policy -- any Policy can be deprecated by having a new Policy with no rules.  An empty policy means it's the dead end of that lineage.  In this example, if you messed up `Y` (successor to `X`) and wanted to retract it, you'd publish an empty `Y'` and _then_ publish `Z` (which also refers to the original `X`).  

It might sound a little complex, but this should be a fairly rare occurrence.  In the future when deciding what constitutes an "active Policy" we can have the server adjudicate all of this in advance, delivering only active and pending Policy objects to the consumer.

**Comment by fractalf** [comment]
Yes, I would dare say it actually **is** a bit complex way of solving this, however I fully understand. It's hard to designe a system/spec that covers all future corner cases etc.

I still see a problem with your latest solution. The proposed empty `Y'` will disable `Y` yes, but I believe it can't be empty as you say, because then there is no rules for this policy at all until `Z` is activated.

**Comment by fractalf** [comment]
Yes, I would dare say it actually **is** a bit complex way of solving this. However I fully understand, it's hard to design a system/spec that covers all future corner cases etc.

I still see a problem with your latest solution. The proposed empty `Y'` will disable `Y` yes, but I believe it can't be empty as you say, because then there is no rules for this policy at all until `Z` is activated? But I understand your idea, so the way to make this work would actually for `Y'` to contain the same rules as `X`, and publish `Y'` immediately. Then `Y` would be disabled and the rules of the old `X` would live on until the corrected `Z` activates.

Am I completely off here or is this actually the final way to solve it (though a bit complex) ?

You are probably right that this should be a fairly rare occurrence, but even so, if it can happen it needs to be handled by the system.

>  In the future when deciding what constitutes an "active Policy" we can have the server adjudicate all of this when queried, delivering only active and pending Policy objects to the consumer.

This. Are there any concrete plans on this? To me this seems like a way to solve this in a better way. That being said, I'm not sure I grasp everything you put into that line, and can see more than one way of actually implementing it :+1:

**Comment by karcass** [comment]
I see why you think my solution is problematic, and I agree that it's a little ambiguous.  Here's a different way to address the "published too soon" problem.

You have existing Policy `X` today.  You wish to replace it with `Y` in two weeks.
You publish `Y` today, with a `start_date` in one week.  One week is supposed to be two weeks.
Publish policy `X'` that is exactly like `X` except it the same `start_date as `Y`, and contains `Y` in its prev_policies.
You have now effectively undone `Y`, and the transition from `X` to `X'` should be seamless.
Now you can publish `Y'` that obsoletes `X'` with the correct date.

**Comment by fractalf** [comment]
Thank you, yes then I with you 100%, this was the only way to solve this edge case. A bit complicated, though for the policies to be immutable I guess it will have to be this way.

What's the main reason(s) that the policies need to be immutable? 

In our case, using an REST API, I can't make much sense of it. I'm curious if you guys have a discussion going on this, especially when it comes to near realtime policies.

Example:
I need to communicate three policies to the providers
1. Parking cap (rules of type _count_ with different _maximum_ values set)
2. Parking fee (rules of type _rate_ with different _rate_amount_ values set)
3. Speed limit (rules of type _speed_ with different _maximum_ values set)

We will always have these policies, but the rules might change ofc. Why would I want to keep these immutable? To me in a realtime scenario it makes more sense to keep this completely dynamic, just updating the rules and telling the providers to poll every x time units. Just remove the start/end date and maybe add another endpoint `/policies/changes` or something to report about planned changes if necessary.

Just thinking out loud here. I've spend a lot of time wrapping my head around how this works, and can't help but feel things can be made easier. Though I'm sure there are other scenarios than mine than maybe needs things to be the way they are, I dunno.

Cheers

**Comment by karcass** [comment]
> What's the main reason(s) that the policies need to be immutable?

Immutable data is the digital version of publishing rules and regulations on paper or via PDF.  

Imagine if all laws were expressed digitally and could be dynamically updated.  Enforcement would be total chaos.  Every court case would be thrown out because you wouldn't be able to prove anything.  You would not be able to go back in time and unambiguously say "these specific rules were in effect at the time that the enforcement occurred".  Every fee or fine would be challenged.  

There are other methods to describe changes to digital rules, of course, but in my experience, immutable data is the most straightforward (even if it doesn't always seem that way).

Going forward, we can extend the Policy API to make the Policy objects refer to URLs that provide dynamic values like speeds, caps, etc.  Those served dynamic values would have to be structured in a fashion that also provides for unambiguous traceability.  This approach would also be incompatible with serving Policy via flat text file, which adds yet another layer of complexity that I think would limit the adoption of this API.

**Comment by fractalf** [comment]
Thank you for your explanation!
As you have made a PR on this I will close this issue
