### ISSUE TITLE
Bring rich telemetry data to Provider Status Endpoint

### ISSUE THREAD

**Issue by quicklywilliam** [openmobilityfoundation/mobility-data-specification#616]
### Is your feature request related to a problem? Please describe.

A remaining inconsistency between Agency and Provider is that the Status endpoint's location data does not include Speed data. This data could be useful in assessing regulatory compliance with speed rules. This data is currently present in Agency, so adding it to Provider would also create greater parity.

### Describe the solution you'd like

Add the speed field to status events in Provider.

### Is this a breaking change

No

### Impacted Spec

 * `provider`

### Additional context

This issue was broken out from #589, which originally requested these data for both Provider endpoints.

**Comment by quicklywilliam** [comment]
I've filed this issue based on the possible use case of wanting to assess compliance with speed-related rules. There may be other regulatory use cases I am overlooking, please chime in if so!

**Comment by schnuerle** [comment]
For some more context, here is what is currently supported in Agency. Note the requirements are all listed as "Required if Available" from the provider.

https://github.com/openmobilityfoundation/mobility-data-specification/tree/release-1.1.0/agency#telemetry-data

Name | Type | Required? | Description
-- | -- | -- | --
gps.lat | Double | Required | Latitude of the location
gps.lng | Double | Required | Longitude of the location
gps.altitude | Double | Required if Available | Altitude above mean sea level in meters
gps.heading | Double | Required if Available | Degrees - clockwise starting at 0 degrees at true North
gps.speed | Float | Required if Available | Speed in meters / sec
gps.accuracy | Float | Required if Available | Accuracy in meters
gps.hdop | Float | Required if Available | Horizontal GPS or GNSS accuracy value (see hdop)
gps.satellites | Integer | Required if Available | Number of GPS or GNSS satellites

**Comment by schnuerle** [comment]
We'll be talking about this at today's [Working Group meeting](https://github.com/openmobilityfoundation/mobility-data-specification/wiki/Web-conference-notes,-2021.06.17-(Joint-Working-Group)).

**Comment by schnuerle** [comment]
Similar to #589, does anyone feel comfortable making a pull request for this, adding the Required if Available fields and others discussed to Provider Trips? There is a PR #73 but I think it's out of date (and the CLA needs to be signed). Could be the same PR.

**Comment by quicklywilliam** [comment]
Addressed by #653.
