### ISSUE TITLE
New city using MDS: Bergen, Norway

### ISSUE THREAD

**Issue by saharald** [openmobilityfoundation/mobility-data-specification#617]
Add Bergen, Norway to the list of cities using MDS.

Suggested tekst

**Bergen, Norway** - is running a [pilot project for shared scooters](https://www.bergen.kommune.no/innbyggerhjelpen/trafikk-reiser-vei/vei-og-veitrafikk/sykkel/elsparkesykler-i-bergen) where the operators must comply with [these guidelines - including data sharing employing MDS Agency API](https://www.bergen.kommune.no/publisering/api/filer/T543853092).

**Comment by karcass** [comment]
Yay!  Exciting!

**Comment by schnuerle** [comment]
Thank you for opening this issue @saharald and welcome! 

I've added your text and links to the latest 1.1.0 release here, which should go live in the next month or two after approval:

https://github.com/openmobilityfoundation/mobility-data-specification/blob/release-1.1.0/README.md#cities-using-mds

**Comment by saharald** [comment]
Excellent - I am excited to join the development of MDS - and spread better solutions for our cities.

**Comment by schnuerle** [comment]
@saharald If you would like to get involved and join the development of MDS, fill out this form to get in touch with us and we could answer your questions about the public MDS [Working Groups](https://github.com/openmobilityfoundation/mobility-data-specification/wiki), how to become a free city [member](https://www.openmobilityfoundation.org/members/), etc. We'd love to know your thoughts and needs in Norway.

https://www.openmobilityfoundation.org/get-in-touch/

**Comment by saharald** [comment]
Great! I am representing a regulation tool for cities and me and/or my colleague will reach out to you soon to get further involved.
