### ISSUE TITLE
[Policy API] support one-time fee after a buffer/duration

### ISSUE THREAD

**Issue by jean-populus** [openmobilityfoundation/mobility-data-specification#632]
### Is your feature request related to a problem? Please describe.

Cities would like to implement a fee if a parked vehicle isn't moved after for example 2 days. This is a one time fee but there's a buffer/duration before it applies.

### Describe the solution you'd like

I'm not sure. We could add a new field for this buffer/duration before the rate is applicable?

### Is this a breaking change

No, I don't think so as this concept doesn't currently exist.

### Impacted Spec

For which spec is this feature being requested?

 * `policy`

**Comment by karcass** [comment]
That's easy with the current Policy.  Two Rules.  One for less-than-duration and one for more-than-duration.

**Comment by jean-populus** [comment]
I'm not sure I follow. Based on the examples, I thought for a one-time fee the variables would be

- rule_type = rate
- rule_units = amount
- rate_amount = user entered
- rate_recurrence = once
- states = available, non-operational

Where does time come in? Should the rule_units = days with min = user entered buffer/duration?

**Comment by karcass** [comment]
So the semantics of having a fee on Rule types other than `rate` is currently ambiguous but easily fixed.  I believe we can simply document the way you can apply a `rate_amount` to a `time` rule.

**Comment by jean-populus** [comment]
Yeah, I think having a rule_type = rate is tripping me up. Why can't we just apply a rate_amount and rate_recurrence to all the rules instead of having a separate "rate" rule?

**Comment by jean-populus** [comment]
The solution you outlined above could then also be applied to my other issue #631 pretty easily.

**Comment by jean-populus** [comment]
thank you @karcass

**Comment by karcass** [comment]
> Yeah, I think having a rule_type = rate is tripping me up. Why can't we just apply a rate_amount and rate_recurrence to all the rules instead of having a separate "rate" rule?

Yes, that is what I'm suggesting.

**Comment by karcass** [comment]
```json
{
  "name": "Buffered One-Time Fee Example",
  "description": "First two hours free, then one-time $4",
  "policy_id": "2800cd0a-7827-4110-9713-b9e5bf29e9a1",
  "start_date": 1558389669540,
  "publish_date": 1558389669540,
  "end_date": null,
  "prev_policies": null,
  "provider_ids": [],
  "rate_recurrence": "once",
  "currency": "USD",
  "rules": [
    {
      "name": "> 2 hours",
      "rule_id": "9cd1768c-ab9e-484c-93f8-72a7078aa7b9",
      "rule_type": "time",
      "rule_units": "hours",
      "geographies": ["0c77c813-bece-4e8a-84fd-f99af777d198"],
      "statuses": { "available": [], "non_operational": [] },
      "vehicle_types": ["bicycle", "scooter"],
      "maximum": 2,
      "rate_amount": 400
    }
  ]
}```

**Comment by jean-populus** [comment]
can be supported with #633 and #631. Closing this issue.
