### ISSUE TITLE
[Policy API] geography_json has UUID type

### ISSUE THREAD

**Issue by pxlrbt** [openmobilityfoundation/mobility-data-specification#635]
**Describe the bug**

In the [Geography's schema description](https://github.com/openmobilityfoundation/mobility-data-specification/blob/1.0.0/policy/README.md#geography) the column `geography_json` is described as "UUID" type. This should probably be of type JSON?

`geography_json	UUID	Required	The GeoJSON that defines the geographical coordinates.`

**Comment by karcass** [comment]
@pxlrbt Good catch!  I'll make a quickie PR.

**Comment by schnuerle** [comment]
Thank you for the catch I updated it for the 1.1.0 release about to come out [here](https://github.com/openmobilityfoundation/mobility-data-specification/commit/a23c3af259499ba7c7df932fc64df15b9f40a140)
