### ISSUE TITLE
Provider Vehicles - Beta 0.4.1 - Feedback 

### ISSUE THREAD

**Issue by schnuerle** [openmobilityfoundation/mobility-data-specification#637]
Gather real world feedback to see how we can move the beta feature [Vehicles](https://github.com/openmobilityfoundation/mobility-data-specification/tree/main/provider#vehicles) out of beta. 

### Describe the solution you'd like

From the MDS Survey, about half of agencies are using Vehicles, most providers are, and almost all companies support it. Seems to have good real world usage. We need feedback here from those that are using it to know what may need to change before it becomes a stable part of MDS.

### Is this a breaking change

 * I'm not sure yet

### Impacted Spec

For which spec is this feature being requested?

 * [provider](https://github.com/openmobilityfoundation/mobility-data-specification/tree/main/provider#vehicles)

### Describe alternatives you've considered

Leave as a beta feature for longer until we have feedback. 

### Additional context

Reviewed as part of the MDS 1.2.0 release review Midway Checkpoint by the Working Group Steering Committees.

**Comment by dirkdk** [comment]
I think soon Vehicles will be a core part of deployment cap enforcement so I think it is a good idea.

**Comment by dirkdk** [comment]
Related, I am wondering if the requirement to also have a GBFS API should be dropped. I'm trying to think back why OMF made this part of the MDS spec https://github.com/openmobilityfoundation/mobility-data-specification#gbfs-requirement

If the reason was compliance checks, I would say the Vehicles endpoint replaces this need and we can drop it. We would like this very much as a provider. This would enable us to use different Quality of Service levels for MDS vs GBFS. For instance, as GBFS is public, we rate limit it but run into problems with data aggregators (@jiffyclub can attest to this) sometimes. If GBFS is not used for compliance anymore we can safely adjust our levels without running the risk of making compliance checks more fragile.

**Comment by schnuerle** [comment]
Thank you for the feedback on Vehicles Dirk.

@dirkdk per your question about GBFS, could you please put that into a new issue for a deeper discussion there?

**Comment by schnuerle** [comment]
See new issue #641 for discussion around GBFS and MDS, and this issue plus the new issue will be the topics at tomorrow's [working group meeting](https://github.com/openmobilityfoundation/mobility-data-specification/wiki/Web-conference-notes,-2021.04.29-(Joint-Working-Group)).

**Comment by jiffyclub** [comment]
We at Populus are now consuming /vehicles and have found it useful in its current spec, so I think it's ready to move out of beta.

**Comment by luisjavierbautista** [comment]
Great idea! In bogota we are starting now with 1.1 version, but put out of beta vehicles endpoint would be great!

**Comment by karcass** [comment]
@jiffyclub good point.  I would propose a uniform timeout for the latest-event-per-vehicle, perhaps longer than 1h.

**Comment by schnuerle** [comment]
Hi all, we had a productive Working Group meeting about this yesterday. Here are the full [meeting notes]().

The ending suggestion is to:
1. Add a definition for 'Jurisdiction' in the _general information_ definitions area of the spec
2. Update vehicles to say "Jurisdiction and/or area of agency responsibility" instead of just PROW.

@dirkdk I know you had to drop off and thought it could just stay as PROW. But we discussed lots of examples where PROW is not adequate (private parking garages, national park areas in a city, just outside of jurisdictions or PROW, within interior sub-cities, etc from notes). What do you think?

@margodawes To clarify your initial concern, do you think that 1) it should be just the PROW as stated, or 2) be larger like the agency jurisdiction and area of responsibility, or 3) do you not care one way or the other and just want it to be more clear?

**Comment by margodawes** [comment]
@schnuerle My initial concern was just about lack of clarity (#3). We think having data on non-PROW vehicle states could be helpful reference, but don't plan to use those data in our fleet size counts, so can do without it.

**Comment by dirkdk** [comment]
> Hi all, we had a productive Working Group meeting about this yesterday. Here are the full meeting notes.
> 
> The ending suggestion is to:
> 
> 1. Add a definition for 'Jurisdiction' in the _general information_ definitions area of the spec
> 2. Update vehicles to say "Jurisdiction and/or area of agency responsibility" instead of just PROW.
> 
> @dirkdk I know you had to drop off and thought it could just stay as PROW. But we discussed lots of examples where PROW is not adequate (private parking garages, national park areas in a city, just outside of jurisdictions or PROW, within interior sub-cities, etc from notes). What do you think?
> 
> @margodawes To clarify your initial concern, do you think that 1) it should be just the PROW as stated, or 2) be larger like the agency jurisdiction and area of responsibility, or 3) do you not care one way or the other and just want it to be more clear?

as long as we keep the list of applicable statuses the same and not list all vehicles in al statuses, this is fine with me. 

This looks more like a semantic discussion then. This definition is easier for providers as I would say, if a user parks the vehicle in a garage that is privately owned that is really hard to track for a mobility provider so we don't. At that point a vehicle is still available for us, in a larger service area.

**Comment by schnuerle** [comment]
I will make a pull request for this with clarifying language and link it here for review.

**Comment by schnuerle** [comment]
I've made PR #665 which removed the beta flag, adds a definition for Jurisdiction, and specifies that vehicles covers Jurisdiction and/or area of responsibility instead of just PROW.

I did not add any more states to the list. Please discuss here if you'd like all state or any more states added and your reasons for it.  [See this comment](https://github.com/openmobilityfoundation/mobility-data-specification/issues/637#issuecomment-839003439) as a start:

> It should be all states. Knowing when and where a vehicle either was picked up, or left the PROW, is important for multiple use-cases including cap-counts.

I did not add guidance on how long vehicles should remain in the vehicles feed after being removed from the PROW, since this may only apply if we add more states. Discuss here if you'd like to see this added. [See this comment](https://github.com/openmobilityfoundation/mobility-data-specification/issues/637#issuecomment-839025647):

> I think that would then require some guidance on how long vehicles should remain in the vehicles feed after being removed from the PROW. We would find it useful to get an update in the vehicles feed about vehicles that have left the PROW, but of course it's not practical to keep all vehicles in there forever. Maybe something like an hour?

and [this comment](https://github.com/openmobilityfoundation/mobility-data-specification/issues/637#issuecomment-839052096):

> I would propose a uniform timeout for the latest-event-per-vehicle, perhaps longer than 1h.

**Comment by jiffyclub** [comment]
+1 for all states, it's useful to know a vehicle was intentionally removed vs. comms were lost or something like that.

**Comment by schnuerle** [comment]
Per our [meeting action items today](https://github.com/openmobilityfoundation/mobility-data-specification/wiki/Web-conference-notes,-2021.08.05-(Joint-Working-Group)#minutes), I've updated the [PR](https://github.com/openmobilityfoundation/mobility-data-specification/pull/665#commits-pushed-c1f619f) and you can see the [changes here](https://github.com/openmobilityfoundation/mobility-data-specification/tree/ms-vehicles-beta/provider#vehicles).

Please leave any feedback as I'd like to get this merged to dev within the next 2 weeks. @dirkdk @bhandzo could weigh in from the provider perspective to ensure providing all states is ok.

**Comment by schnuerle** [comment]
Planning to resolve and merge this PR within a week or so, so please weigh in soon if you have thoughts.

**Comment by schnuerle** [comment]
Closed with #665
