### ISSUE TITLE
[Geography] Clarification on geography_type: Area controlled by an agency

### ISSUE THREAD

**Issue by mrsimpson** [openmobilityfoundation/mobility-data-specification#660]
## Motivation
We're building a system with support for multiple cities. Each of those shall be able to only access data within their jurisdiction.
As per the definition of those areas, we were looking into the `geographies` endpoint which as per our understanding is referred to in `jurisdictions`.

## Question and context
As per [the current geography types](https://github.com/openmobilityfoundation/mobility-data-specification/blob/main/geography/README.md#geography-type), there was no obvious choice for a geography type: While most of the times, a municipal boundary is the basis for the area in control, it may deviate (e. g. the area might be enlarged slightly in order to handle edge-cases (literally)). Is `overlay_district` the semantic we're looking for?

**Comment by schnuerle** [comment]
Note that the `geography_type` field is just a recommendation of possible values.  You may create your own. If you do you can record it here to be added to the list in a future release. From the spec:

"These specific types are recommendations based on ones commonly defined by agencies. Others may be created by the Agency as needed..."

I think you are looking for something that is not here, but has been discussed. Kine of like an `area_of_responsibility` that is larger than the jurisdiction. This happens in Louisville, but that area is not concretely defined (though maybe should be).

**Comment by mrsimpson** [comment]
> Note that the geography_type field is just a recommendation of possible values

Yes, we've seen that. We actually already implemented it as `agency_area`, I just wanted to clarify about the possible equal semantics of `overlay_district`.
But as I understood now, this is something else => closing this issue here. Thanks, @schnuerle
