### ISSUE TITLE
Add vertical_accuracy field and rename 'accuracy' to 'horizontal_accuracy'

### ISSUE THREAD

**Issue by quicklywilliam** [openmobilityfoundation/mobility-data-specification#661]
### Is your feature request related to a problem? Please describe.

In #653 we chose not to add vertical accuracy to keep things consistent with the existing implementation in Agency. This issue is being filed so that in a future breaking release we can make this change in both Provider and Agency.

### Describe the solution you'd like

Add new `vertical_accuracy` field to Geographic Telemetry Data and Agency Telemetry objects. Also, rename existing `accuracy` field to `horizontal_accuracy`.

### Is this a breaking change

 * Yes, breaking

### Impacted Spec

For which spec is this feature being requested?

 * `agency`
 * `provider`

**Comment by schnuerle** [comment]
To be resolved with PR #796
