### ISSUE TITLE
Version number is 1.0.x for 1.1.0 release

### ISSUE THREAD

**Issue by paultbeck** [openmobilityfoundation/mobility-data-specification#669]
**Describe the bug**
The schemas for provider endpoints in the release-1.1.0 branch seem to have 1.0.x versions, which prevents validating responses using the schemas in https://github.com/openmobilityfoundation/mobility-data-specification/tree/release-1.1.0/provider

**To Reproduce**
* Create a /trips response with "version": "1.1.0" in the payload
* Validate the schema using https://github.com/openmobilityfoundation/mobility-data-specification/blob/release-1.1.0/provider/trips.json
* Observe that '1.1.0' does not match '^1\\.0\\.[0-9]+$'

**Expected behavior**
* https://github.com/openmobilityfoundation/mobility-data-specification/blob/release-1.1.0/provider/trips.json can be used to validate a valid version 1.1.0 /trips response

**Additional context**
The [release process](https://github.com/openmobilityfoundation/governance/blob/main/technical/ReleaseGuidelines.md#preparing-a-release-candidate) seems to be very specific about how this is updated, but unless I'm mistaken, it wasn't done for 1.1.0.

**Comment by schnuerle** [comment]
Tagging @thekaveman for review and feedback. Could be a simple PR to fix in upcoming 1.2.0 release.

**Comment by paultbeck** [comment]
Thanks! I'm happy to put up a PR but it seems like 1.1.0 is baked and the next opportunity will be when the release-1.2.0 branch is created.

**Comment by thekaveman** [comment]
Doh!! 😱 yes this is definitely a bug in the 1.1.0 schema. This obviously must be fixed for the 1.2.0 release.

Depending on the scope of 1.2.0 changes, it may make sense to release a hotfix 1.1.1 that updates the schemas for anyone wanting to stick to the 1.1.x line.

> ...next opportunity will be when the release-1.2.0 branch is created

No need to wait until then - a PR against `dev` can be made now to fix this for the forthcoming 1.2.0.

If there is a feeling that a 1.1.1 hotfix is warranted, a PR against `main` a la the [Hotfix Releases guidelines](https://github.com/openmobilityfoundation/governance/blob/main/technical/ReleaseGuidelines.md#hotfix-releases) would be the next step. But unlike what the guidelines state (step 4), the changes required for the hotfix are independent of the changes required for 1.2.0, so two distinct PRs/branches/commits would be needed.

**Comment by schnuerle** [comment]
I'll definitely make a PR and merge to `dev` to fix this for 1.2.0.

It could also be good to make a PR and hotfix the 1.1.0 release with 1.1.1 against `main`. I'm on the fence since 1.2.0 will be finished soon (1-2 months till approval). But if anyone feels strongly about it, they can make a PR for this.

Thank you for catching this @paultbeck - it's something I should have seen when creating the release. We had a number of beta features which didn't have schema updates, so I wasn't giving the schema the attention it deserved.

**Comment by schnuerle** [comment]
Fixed for 1.1.1 with PR #699. Please review @paultbeck for accuracy. I will create the release tomorrow.
