### ISSUE TITLE
Policy Rule Type: Rates - Beta 1.0.0 - Feedback

### ISSUE THREAD

**Issue by schnuerle** [openmobilityfoundation/mobility-data-specification#674]
Gather feedback to see how we can move [Policy Rule Type: Rates](https://github.com/openmobilityfoundation/mobility-data-specification/tree/main/policy#rule-types) out of beta. 

### Describe the solution you'd like

Collect enough feedback, real-world usage, and requested updates/improvements to move this feature out of beta in a future release

### Is this a breaking change

 * Not sure yet

### Impacted Spec

For which spec is this feature being requested?

 * Policy

### Describe alternatives you've considered

Leave as a beta feature for longer until we have feedback. 

### Additional context

All beta features once part of an official release receive an Issue like this to gather feedback.

**Comment by schnuerle** [comment]
Looking to move this out of beta for 2.0 for both the Policy and the Provider/Agency Unification work efforts.

**Comment by schnuerle** [comment]
I believe that PR #796 and others allow Rates to be moved out of beta, or are Rates removed entierly?

**Comment by jean-populus** [comment]
Rates as a rule type have been removed entirely but the fields can be
applied to any rule type now. I think the question is then whether the
Rates fields can be moved out of beta? My vote would be yes.

**Comment by schnuerle** [comment]
Moved out of beta.
