### ISSUE TITLE
OpenMobilityData source code

### ISSUE THREAD

**Issue by gtfs0** [openmobilityfoundation/mobility-data-specification#676]
Where can I get the source code for the OpenMobilityData web application?
The github page https://github.com/OpenMobilityData seems to be gone, I get a 404 error when trying to access it.

**Comment by schnuerle** [comment]
Could you specify in more detail what sort of source code you are looking for? The page at https://github.com/OpenMobilityData is not owned or run by the OMF, which only manages this organization: https://github.com/openmobilityfoundation
