### ISSUE TITLE
Provider Events: Is it used, useful, redundant, or should be deprecated?

### ISSUE THREAD

**Issue by schnuerle** [openmobilityfoundation/mobility-data-specification#679]
### Is your feature request related to a problem? Please describe.

Should the [Provider /events endpoint](https://github.com/openmobilityfoundation/mobility-data-specification/tree/main/provider#events) be deprecated and removed in a future major MDS release since /status_changes and /vehicles (improved in 1.2.0) now seem to cover the same data scenarios? 

Who is using /events now?

- Bird is sending it, Vianova/Populus support it (but maybe not using the data)
- Blue Systems is using it, but could do without it
- Related: does adding a vehicle filter by vehicle_id back into /events help make it more useful?

### Describe the solution you'd like

Have cities, providers, and software companies chime in to say if they use Events, how they use Events, if they would mind if Events was removed, and/or if adding any features to Events would make it more useful.

### Is this a breaking change

 * Yes, breaking

### Impacted Spec

 * `provider`

### Describe alternatives you've considered

Will continue to support Events until there is wide consensus that it is not valuable any more.

### Additional context

This was brought up in a recent [working group meeting](https://github.com/openmobilityfoundation/mobility-data-specification/wiki/Web-conference-notes,-2021.08.05-(Joint-Working-Group)#minutes).

**Comment by S-eb** [comment]
Team,

following up on the discussion we had on August 5th, confirming that at Blue Systems we connect to this /events endpoint in the provider api but we could do without it.

Seb

**Comment by schnuerle** [comment]
With the work on 2.0 and #796, Events will remain and gets some details like recent and historic, and status changes moves under vehicles.
