### ISSUE TITLE
"removed" missing "comms_restored" option in provider schemas

### ISSUE THREAD

**Issue by davenguyen** [openmobilityfoundation/mobility-data-specification#690]
**Describe the bug**
The "status_changes" provider schema is missing the "comms_restored" event type under the "removed" vehicle_state. It's missing on both 1.0.0 and 1.1.0 schema.

I assume since the state machine diagram has "**Unknown** can go to any state with event_type _comms_restored_, _located_, _unspecified_", this should be included for "removed" as well.

**To Reproduce**

See schemas for each version:

- 1.0.0: https://github.com/openmobilityfoundation/mobility-data-specification/blob/release-1.0.0/provider/status_changes.json#L418
- 1.1.0: https://github.com/openmobilityfoundation/mobility-data-specification/blob/release-1.1.0/provider/status_changes.json#L418

**Expected behavior**

`comms_restored` should be added to "event_types" -> "contains" -> "enum" under `removed`.

**Additional context**

None.

**Comment by schnuerle** [comment]
Fixed for 1.1.1 with PR #699. Please review @davenguyen for accuracy. I will create the release tomorrow.
