### ISSUE TITLE
Include Bridge Names for Routes Heatmap in Portland Mapviews

### ISSUE THREAD

**Issue by mschwartzie** [openmobilityfoundation/mobility-data-specification#691]
Similar to the Open Data Portal, for some reason a number of bridge links in the routes heatmap do not include names/labels when clicking on them. Customer has requested this to be updated because bothering him given that they are some of the most traveled routes. This would need to be updated for scooters, BIKETOWN, BIKETOWN Stations, and carshare mapviews.

Mike Guida (can't find his Github username to tag him) has context and was able to make this change relatively quickly in ODP. 

![Screen Shot 2021-09-03 at 10 16 59 AM](https://user-images.githubusercontent.com/25393854/132020230-462cb527-93ea-4397-b7fa-7c18580432e1.png)

**Comment by schnuerle** [comment]
Could you post a link to the website this map appears on? I don't think that MDS will help you here, as road/bridge names are not included in MDS.
