### ISSUE TITLE
New vehicle_types

### ISSUE THREAD

**Issue by sven4all** [openmobilityfoundation/mobility-data-specification#692]
I created an issue in the GBFS repository to add new form_factors (in MDS vehicle_types) https://github.com/NABSA/gbfs/issues/365. Because GBFS and MDS are using the same values I would like to ask the MDS community also about an opinion. Please leave your comments in the GBFS issue https://github.com/NABSA/gbfs/issues/365, if there is agreement I would like to make the same proposal for new form_factors/vehicle_types in GBFS as in MDS.

### Is this a breaking change
 * No, not breaking

**Comment by schnuerle** [comment]
Thank you for cross posting this which helps us stay in alignment. For MDS 2.0 in a few months we will be making major changes to the vehicle types, properties, and modes in MDS, so it seems like a good time to make updates like this as well.  If the change on the GBFS side comes sooner (in the next few weeks or so) we may be able to discuss and add it for MDS 1.2 more quickly.

**Comment by schnuerle** [comment]
Per PR https://github.com/NABSA/gbfs/pull/370, for MDS 1.2.0 we _may_ be able to add `cargo_bicycle` as a vehicle type, but would not be able to remove `scooter` as this would be a breaking change. So we would have to revisit later to align these changes to MDS in the next major release 2.0.0, which will start work in the next few weeks. 

We can see how the GBFS work progresses in the next few weeks and I could add `cargo_bicycle` as a new option for 1.2.0.

**Comment by sven4all** [comment]
That would be great, is it also possible to add the maximum speed?

**Comment by schnuerle** [comment]
Per our public working group discussions yesterday, we will add `cargo_bicycle` as a new vehicle type in 1.2. I'll make a PR for that in the next few days. Other vehicle types may be added in 2.0 when we look at new modes.

For vehicle properties like max speed, we are also going to hold off for 2.0 since it's not clear yet if GBFS will be adding these as is, MobilityData is looking at creating a whole new way to express vehicle properties in the next 3.0 breaking release, and MDS will also look at vehicle properties/attributes in 2.0.

We will keep this issue open for discussion during 2.0 development.

**Comment by schnuerle** [comment]
Per [this comment](https://github.com/openmobilityfoundation/mobility-data-specification/pull/698#issuecomment-926142087) I updated all existing vehicle type definitions, which are certainly more accurate that the existing ones and have less definitional overlap. 

Note that GBFS does not have definitions yet for the same vehicle types.

These can be changed based on community feedback in the coming weeks as we work on approval for the 1.2 release candidate. They can be further expanded and refined in the 2.0 release.

**Comment by jiffyclub** [comment]
Linking to the [GBFS vehicle types spec](https://github.com/NABSA/gbfs/blob/master/gbfs.md#vehicle_typesjson), which as of `v2.3-RC2` includes the following "form factors":

- bicycle
- cargo_bicycle (added in v2.3-RC2)
- car
- moped
- scooter_standing (standing kick scooter, added in v2.3-RC2)
- scooted_seated (this is a kick scooter with a seat, not to be confused with moped, added in v2.3-RC2)
- other

At Populus we are seeing use cases for being able to differentiate standing and seated scooters, it'd be great to get that included in MDS 2.0.

**Comment by kheraankit** [comment]
+1 from Lime as well to add separate [scooter_standing, scooter_seated]  

We have been getting requests from a few cities that want to be able to distinguish between standing and seated scooters.  

@schnuerle I understand that changing the definition of the scooter will be a breaking change and should be done as part of a major release.  Is there a timeline for the 2.0 release?

> Linking to the [GBFS vehicle types spec](https://github.com/NABSA/gbfs/blob/master/gbfs.md#vehicle_typesjson), which as of `v2.3-RC2` includes the following "form factors":
> 
> * bicycle
> * cargo_bicycle (added in v2.3-RC2)
> * car
> * moped
> * scooter_standing (standing kick scooter, added in v2.3-RC2)
> * scooted_seated (this is a kick scooter with a seat, not to be confused with moped, added in v2.3-RC2)
> * other
> 
> At Populus we are seeing use cases for being able to differentiate standing and seated scooters, it'd be great to get that included in MDS 2.0.

**Comment by schnuerle** [comment]
We may be able to add this for 2.0. We need to see how the dust settles on all the streams of work this week to decide how and where to add it.

**Comment by schnuerle** [comment]
> That would be great, is it also possible to add the maximum speed?

Hi @sven4all - when you say maximum speed, do you mean the maximum possible speed for the vehicle. E.g., maybe 30kph for a scooter, but 150kph for a car? Or do you mean maximum allowed speed, like the fields GBFS uses (they don't specify max possible speed).

**Comment by schnuerle** [comment]
See #833 for all the updated details for MDS 2.0, including aligning with GBFS on vehicle and propulsion types, and adding maximum speed. Leave feedback here as a comment or in the PR. We will merge to dev tomorrow, though there will be time for more comments/adjustments in the coming weeks as we go through the OMF approval process. cc @mplsmitch

**Comment by schnuerle** [comment]
Feel free to leave comments and we can catch tweaks in the review process.
