### ISSUE TITLE
Clarification needed on possible values of `rule_units`

### ISSUE THREAD

**Issue by janedotx** [openmobilityfoundation/mobility-data-specification#704]
### Is your feature request related to a problem? Please describe.

In the policy README,  `rule_units` is `amount` for a rate rule type, but it could be a unit of time instead if the rate rule has a recurrence of `each_time_unit` or `per_complete_time_unit`.

### Describe the solution you'd like

Get rid of `amount` as a valid value for `rule_units`. There doesn't seem to be much point in having `rule_units` have a value of `amount` just for rate rules that recur only once.

### Is this a breaking change

I don't think this is breaking. If you write a recurring rate rule, you already have to set `rule_units` to some sort of time unit to have the rule make sense in the first place.

 * No, not breaking

### Impacted Spec

For which spec is this feature being requested?

 
 * `policy`

### Describe alternatives you've considered

We could leave it as is, but it seems very confusing to me.

**Comment by Penleebv** [comment]
"Appreciation Very bless".

**Comment by schnuerle** [comment]
This may be addressed as part of the Policy re-work lead by @S-eb and @jean-populus.

**Comment by jean-populus** [comment]
I believe `rate` as been removed a `rule_unit` with this PR https://github.com/openmobilityfoundation/mobility-data-specification/pull/806
