### ISSUE TITLE
Unlocking method

### ISSUE THREAD

**Issue by mattwigway** [openmobilityfoundation/mobility-data-specification#71]
In the trips dataset, it would be useful to know how the user unlocked the dockless vehicle (e.g. smartphone, keypad, keycard, etc). Here in Phoenix, one of the dockless systems (GRiD/Social Bicycles) unlocks with a keypad or an RFID card.

**Comment by hunterowens** [comment]
PR welcome!

**Comment by schnuerle** [comment]
Is this important for regulators to know in MDS? This seems more useful for GBFS with a public facing endpoint since it impacts how someone may use a vehicle.

**Comment by schnuerle** [comment]
I'm going to close this as it is more appropriate in a traveller facing feed like GBFS. Cities may not provide this data using MDS, even if they run their own bike/scooter share, and instead the info would come from those devices's GBFS feeds.
