### ISSUE TITLE
Multiple `provider_ids` in Cap Policy

### ISSUE THREAD

**Issue by jackdreillyvia** [openmobilityfoundation/mobility-data-specification#714]
### Discussed in https://github.com/openmobilityfoundation/mobility-data-specification/discussions/708

<div type='discussions-op-text'>

<sup>Originally posted by **jackdreillyvia** October 22, 2021</sup>
[This single-provider-cap](https://github.com/openmobilityfoundation/mobility-data-specification/blob/main/policy/examples/provider-cap.json) example policy applies a cap to a single provider.

What is the interpretation of a cap policy when `provider_ids` is empty or has multiple values? Does it mean that the cap applies independently to each provider, or that the cap is set on the sum of devices summed across all providers in the list (or all providers in the city if `provider_ids` is empty)?</div>

**Comment by schnuerle** [comment]
If you'd like to make PR about this, please do. Thank you!

**Comment by schnuerle** [comment]
If you'd like to make a PR for this based on the new MDS 2.0 please do and we can reopen.
