### ISSUE TITLE
Add Provider ID: ATOM Mobility

### ISSUE THREAD

**Issue by Igors5** [openmobilityfoundation/mobility-data-specification#721]
1. **provider_name** - ATOM Mobility
2. **provider_id** - 4d88272c-032e-487c-9f58-ab5951a23427
3. **url** - https://atommobility.com
4. **mds_api_url** - https://mds.rideatom.com/mds
 
GBFS API url will be added later.
Igors, developer@ATOM Mobility

**Comment by schnuerle** [comment]
I've added a draft of this to the CSV file here for you to review:

https://github.com/openmobilityfoundation/mobility-data-specification/blob/ms-identifiers-1/providers.csv

**Comment by Igors5** [comment]
all good! thanks.
