### ISSUE TITLE
Add Provider ID: LEO Ride

### ISSUE THREAD

**Issue by eldadberko** [openmobilityfoundation/mobility-data-specification#723]
**Note:** See the [Adding an MDS Provider ID](https://github.com/openmobilityfoundation/mobility-data-specification/wiki/Adding-an-MDS-Provider-ID) page for more help.

Opening this issue will allow you as a mobility service provider get an official provider ID for use across MDS globally.

**Fields needed from you for the [providers.csv file](https://github.com/openmobilityfoundation/mobility-data-specification/blob/main/providers.csv).**

_All fields are required._

1. **provider_name** - LEO Ride
   - ...
1. **provider_id** - 7b0eedf6-c7a5-4262-9222-ab2484ad214e
   - ...
1. **url** - https://leoride.co/

1. **mds_api_url** -  https://mobile.leoriders.com/mds
1. **gbfs_api_url** - https://mobile.leoriders.com/gbpf
   - ...

Additionally, please provide your name and role within your agency to help with verification.

**Comment by schnuerle** [comment]
Which info should we add for LEO Ride? There is this issue, and also issue #724 

This one has MDS and GBFS urls (though the GBFS one ends with gbpf - is this correct?).

**Comment by eldadberko** [comment]
YES please.

**Comment by schnuerle** [comment]
I've added a draft of this to the CSV file here for you to review:

https://github.com/openmobilityfoundation/mobility-data-specification/blob/ms-identifiers-1/providers.csv

Please confirm that the GBFS url ends in GBPF...

**Comment by eldadberko** [comment]
Thanks,

Confirmed

**Comment by eldadberko** [comment]
Thanks a lot

**Comment by TiphaineLAURENT** [comment]
FYI, there is a typo on LEO Ride id. It is missing the first character `7`

**Comment by schnuerle** [comment]
Yes agree the UUID should be `7b0eedf6-c7a5-4262-9222-ab2484ad214e`. It can be fixed in a pull request to `dev`, and will go to `main` in whatever the next release is.
