### ISSUE TITLE
Add Provider ID: LEO Explore

### ISSUE THREAD

**Issue by AndrewBlinnikov** [openmobilityfoundation/mobility-data-specification#724]
1. **provider_name** - LEO Explore
2. **provider_id** - 7c653014-2f33-4f5b-98de-30ea66430986.
3. **url** - https://leoride.co/
4. **mds_api_url** - 
5. **gbfs_api_url** - 

MDS and GBFS API URLs will be added later.
Andrew, project manager Leo Explore

**Comment by schnuerle** [comment]
Which info should we add for LEO Ride? There is this issue, and also issue #723. 

The other one has MDS and GBFS urls too.

**Comment by AndrewBlinnikov** [comment]
> Which info should we add for LEO Ride? There is this issue, and also issue #723.
> 
> The other one has MDS and GBFS urls too.

Hi, those requests are separate, Leo Explore and Leo Ride are different applications from the same service provider

**Comment by schnuerle** [comment]
I've added a draft of this to the CSV file here for you to review:

https://github.com/openmobilityfoundation/mobility-data-specification/blob/ms-identifiers-1/providers.csv
