### ISSUE TITLE
Add Provider ID: TukTuk

### ISSUE THREAD

**Issue by saurabh-ecsion** [openmobilityfoundation/mobility-data-specification#726]
**Note:** See the [Adding an MDS Provider ID](https://github.com/openmobilityfoundation/mobility-data-specification/wiki/Adding-an-MDS-Provider-ID) page for more help.

Opening this issue will allow you as a mobility service provider get an official provider ID for use across MDS globally.

**Fields needed from you for the [providers.csv file](https://github.com/openmobilityfoundation/mobility-data-specification/blob/main/providers.csv).**

_All fields are required._

1. **provider_name** - "tuktuk"
   - ...
1. **provider_id** - "1a99bf67-14a0-48a1-98d1-77147a88c3d2"
   - ...
1. **url** - "https://tuktukscooters.com/"
   - ...
1. **mds_api_url** - "https://app.tuktukscooters.com/mds-feed"
   - ...
1. **gbfs_api_url** - "https://app.tuktukscooters.com/gbfs-feed"
   - ...

Additionally, please provide your name and role within your agency to help with verification.

Saurabh Wankhede, Ecsion Inc. Developer

**Comment by schnuerle** [comment]
I will create a Pull Request to add this to the MDS `dev` branch. 

Is the name "tuktuk", or "TukTuk" with capitalization? The website logo and About Us page uses capitalization.

**Comment by ecsion** [comment]
Hi, You can use the capitalization. Thank you for pointing this out. We were under the impression to take out capitalization and that is why Saurabh submitted tuktuk instead of TukTuk.

**Comment by saurabh-ecsion** [comment]
Hi,

**Comment by schnuerle** [comment]
Added to `dev` with pull request #730

**Comment by ecsion** [comment]
Thank you

**Comment by saurabh-ecsion** [comment]
Hi,

We have provided you provider id *1a99bf67-14a0-48a1-98d1-77147a88c3d2* and you have added *1a99bf67-14a0-48a1-98d1-77147a88c3d* in https://github.com/openmobilityfoundation/mobility-data-specification/blob/dev/providers.csv which is invalid UUID. 

Please update correct provider id (*1a99bf67-14a0-48a1-98d1-77147a88c3d2*) in provider.csv and let us know.

**Comment by schnuerle** [comment]
Hello @saurabh-ecsion I'm sorry that was my mistake! It is now corrected in the `dev` branch.

https://github.com/openmobilityfoundation/mobility-data-specification/blob/dev/providers.csv
