### ISSUE TITLE
Open ended policy

### ISSUE THREAD

**Issue by S-eb** [openmobilityfoundation/mobility-data-specification#727]
### Is your feature request related to a problem? Please describe.

Some cities express the need to define a policy without an end date. For example: "speed is limited to 10 mph in a given area."
It is expected that speed will be limited to 10 mph until further notice, so no end date is defined per se.
The current MDS policy implementation imposes 
 *  to publish an ```end date``` using an arbitrary date;
 *  once the policy needs to change, to replace this policy with a new one with a revised ```end date```

### Describe the solution you'd like

To achieve the need above, it may be interesting to allow the creation of policy without and end_date (the semantic to be used can be further refined) and allow in a second step to set an end_date for the policy. This would require also the implementation of #529 
making the ```end_date field``` editable

### Is this a breaking change

Similarly to #529, this could be implemented in a non breaking way.

 * No, not breaking

### Impacted Spec

For which spec is this feature being requested?

 * `policy`

### Describe alternatives you've considered

Keep current date process

**Comment by jean-populus** [comment]
Is this still a pressing issue we want to address or is it ok to close it for now?
