### ISSUE TITLE
maintenance events definition

### ISSUE THREAD

**Issue by S-eb** [openmobilityfoundation/mobility-data-specification#728]
### Is your feature request related to a problem? Please describe.

Agencies may impose that a device should pass a maintenance check on a periodic basis, for safety reasons.
This could be done by using a time policy and the maintenance associated events, but would require agreement on the `maintenance`, and `maintenance_pick_up` events definition.

### Describe the solution you'd like

It might be interesting to specify the precise situation the events `maintenance `and `maintenance_pick_up` can be used, so that an agency can control indeed if a device passed the required periodic checks.  Can the `maintenance `events be used for such a check ?
Is the `maintenance_pick_up` more appropriate?

### Is this a breaking change

Depending on the agreement regarding event definition, some adjustment may be required by the providers;
 * I'm not sure

### Impacted Spec

For which spec is this feature being requested?

 * `agency`
 * `provider`

### Describe alternatives you've considered

An alternatives would be to create new events. However this would probably require bigger changes to existing implementations.

**Comment by schnuerle** [comment]
If we can agree on the definitions here and a preferred implementation of this in Policy, I think we can clarify this for 2.0.

@S-eb says on call it's important to determine when maintenance checks are happening.

**Comment by joshuaandrewjohnson1** [comment]
A few thoughts here, and welcome @bhandzo or @ezmckinn to weigh in from operator perspective as well. 

We have a number of cities where we report vehicle maintenance activities via flat file, and I'd suggest that the Reports API might be a good starting point if there is a desire for that data to go through MDS.

I have questions about the standards that would be set if we are to do this through the Policy API, like how is the appropriate number of days determined for maintenance to be performed, and is there any demonstrated or documented need for maintenance/inspection that shows improved operator practices or safety outcomes? Would like to hear city perspectives on how appropriate policies would be developed related to maintenance activities, aside from just reporting. 

Also there is no way to monitor via MDS whether any inspection or maintenance was actually performed when there is an event change.

**Comment by jean-populus** [comment]
Is this still a pressing issue we want to address or is it ok to close it for now?

**Comment by schnuerle** [comment]
Going to close for now but @S-eb reopen or create a new issue if something like this is needed.
