### ISSUE TITLE
Use case short list for policy reimagining task force

### ISSUE THREAD

**Issue by S-eb** [openmobilityfoundation/mobility-data-specification#752]
### Is your feature request related to a problem? Please describe.

After discussion with several stakeholders, this is the policy shortlist on which we would like to base the work of the policy task force.

| Name | Rank | Dynamically changing | Comments / areas of improvement | [Use Case ID](https://airtable.com/shr2cnPQvKjzONJpG/tblzFfU6fxQm5Sdhm) |
|-- | -- | -- | -- | -- |
| Operating Area | 1 | No | jurisdiction where operations are permitted |  OMF-MDS-34 |
| No Riding | 2 | Yes |  | OMF-MDS-32 |
| No Parking | 3 | Yes |  | OMF-MDS-35 |
| Required Parking | 4 | Yes |  | OMF-MDS-37 |
| Preferred Parking | 5 | Yes | group with required parking | OMF-MDS-2 |
| Parking Time Limit | 6 | Yes |  |  |
| Speed Limits | 7 | No | guidelines for better accuracy via better telemetry | OMF-MDS-36 |
| Distribution Policies | 8 | No | Associated with equity distribution or over concentration | OMF-MDS-2 |
| Provider Caps or Minimums | 9 | No | including fees | OMF-MDS-43 |
| Maintenance | 10 | Yes | operators have to do a maintenance check every x days |  |
| Emergency guidance | 11 | Yes | special instructions in case of a sudden event | OMF-MDS-38 |

_Note: @schnuerle updated table to add use case links by ID_

### Describe the solution you'd like

No functional solution yet. We would like confirmation that these use cases are the most important.

### Is this a breaking change

Not yet assessed

### Impacted Spec

To be further analyzed

 * `agency`
 * `policy`
 * `provider`

### Describe alternatives you've considered
N/A

### Additional context

The Policy reimagining taskforce is working on the MDS 2.0 evolutions for greater adoption of the MDS policy.
The idea is to
* identify key policy use cases 
* analyze how these policies are implemented today
* make recommendations on potential evolutions

**Comment by schnuerle** [comment]
Note I updated the table to add use case links by ID to our Use Case Database where relevant.

**Comment by schnuerle** [comment]
We will be talking about this at this week's [MDS meeting](https://github.com/openmobilityfoundation/mobility-data-specification/wiki/Web-conference-notes,-2022.06.23-(MDS-Working-Group)).

**Comment by jean-populus** [comment]
This has been taken into account in #764
