### ISSUE TITLE
Align the property names `publish_date` and `published_date` in geography/policy API

### ISSUE THREAD

**Issue by d-koppenhagen** [openmobilityfoundation/mobility-data-specification#757]
### Is your feature request related to a problem? Please describe.

Currently there is a property `publish_date` in the geography API and a similar property named `published_date` in the policy API.

### Describe the solution you'd like

Both property names should be aligned to either `publish_date` or `published_date` (but consistent).

### Is this a breaking change

A breaking change would require consumers or implementors of the API to modify their code for it to continue to function (ex: renaming of a required field or the change in data type of an existing field). A non-breaking change would allow existing code to continue to function (ex: addition of an optional field or the creation of a new optional endpoint). 

* Yes, breaking

### Impacted Spec

For which spec is this feature being requested?

 * `geography`
 * `policy`

### Describe alternatives you've considered

None

### Additional context

The current specification with the inconsistency in the naming can lead to confusions in the implementation as seen in the mds-core implementation:
https://github.com/lacuna-tech/mds-core/issues/973

**Comment by marie-x** [comment]
🤦‍♀️

**Comment by schnuerle** [comment]
Resolved with #784, thank you!
