### ISSUE TITLE
Ambiguous version string in media-type header

### ISSUE THREAD

**Issue by nshi** [openmobilityfoundation/mobility-data-specification#766]
**Describe the bug**
[This section](https://github.com/openmobilityfoundation/mobility-data-specification/blob/main/general-information.md#versioning) describes the version string in the media-type as a dot-separated string with major and minor version, but the examples below are in mixed forms `1.0.1` and `1.2`. It is ambiguous whether the patch version is required or optional. In [the schema](https://github.com/openmobilityfoundation/mobility-data-specification/blob/main/schema/templates/common.json#L719), it is clear that the patch version is **required** since at least version 0.3.0.

Due to this ambiguity in the spec, some providers return HTTP 406 when the patch version is specified in the media-type header and some return the same error when it's not specified.

**To Reproduce**
Please see the links to the two pages in the spec for examples.

**Expected behavior**
Clearly and consistently document whether the patch version is required or not in the schema and the spec. All examples should also follow the same decision.

**Additional context**
None

**Comment by schnuerle** [comment]
Fixed in PR #830 in line 259 of [this commit](https://github.com/openmobilityfoundation/mobility-data-specification/pull/830/commits/5f9430eed5abde4e7b75bc66fe78006effb4f83c#diff-4451bc82090b96dc498275d81fc5a1649dac2be184ee14b7decf469295e59e2fR259).

**Comment by nshi** [comment]
Thank you!
