### ISSUE TITLE
Please add our provider ID to Main branch

### ISSUE THREAD

**Issue by ecsion** [openmobilityfoundation/mobility-data-specification#773]
Previously you established a provider ID in Dev Branch and now we need the same ID for Main branch

Previous request is here: https://github.com/openmobilityfoundation/mobility-data-specification/issues/726

**Comment by schnuerle** [comment]
Hi @ecsion we won't be updating the `main` branch until the next MDS release, which is 2.0. You can see [progress on the release work here](https://github.com/openmobilityfoundation/governance/wiki/Release-2.0.0). 

But you can still reference the `dev` branch and start using your ID now, per our [guide](https://github.com/openmobilityfoundation/mobility-data-specification/wiki/Adding-an-MDS-Provider-ID#using-your-id).
