### ISSUE TITLE
status_changes incomplete data status code representation

### ISSUE THREAD

**Issue by tadam313** [openmobilityfoundation/mobility-data-specification#775]
### Is your feature request related to a problem? Please describe.

MDS 1.2 specification states the following about `provider/status_changes` endpoint response:

> For hours that are in the past but for which data is not yet available the API shall return a 102 Processing response.

Using HTTP 102 could be problematic in some contexts as it was originally designed for [WebDAV](https://datatracker.ietf.org/doc/html/rfc2518#section-10.1) and is also not part of HTTP 1.0 specification. It is designed for long-running operations with a "progress" semantic/reporting which can not be easily applied for status changes processed later on (such as trips). Response timeouts (due to long-living connections) and [reverse-proxy](https://github.com/envoyproxy/envoy/issues/18844) support can also be problematic

### Describe the solution you'd like

Preferably using other status codes which are more backward compatible with HTTP 1.0 and also easier to use in any context.

### Is this a breaking change

 * Potentially if clients count on it

### Impacted Spec

 * `provider`

### Describe alternatives you've considered

Suggestion: use `HTTP 202 Accepted`. [By design](https://www.rfc-editor.org/rfc/rfc9110.html#section-15.3.3) it's a noncommittal status code that indicates that the request is acted upon but the content might be partial. The client in this case would need to re-request the status changes later on until `HTTP 200 OK` is seen which indicates completeness.

**Comment by schnuerle** [comment]
Thoughts on this @avatarneil @marie-x ?
