### ISSUE TITLE
Guidance on deactivating policies that are mistakes? 

### ISSUE THREAD

**Issue by janedotx** [openmobilityfoundation/mobility-data-specification#779]
### Is your feature request related to a problem? Please describe.

We're writing a policy authoring tool now and we're considering the use case where a user makes a policy, publishes it, realizes there's a mistake, and needs to deactivate immediately. We feel that it doesn't make a lot of sense for the deactivating policy to have a `start_date` that needs to be at least 20 minutes after a `publish_date` in the case of a deactivating policy. Should an exception be made for deactivating policies? We do want to be sensitive to the needs of providers in staying informed of what policies are currently active, but providers shouldn't need to know about faulty policies and the deactivation polices designed to neutralize them. (We think a deactivation policy could be marked as a deactivation policy if it contains one `UUID` in `prev_policies` and contains no rules.) What are other people's thoughts? 

### Describe the solution you'd like

This could be clunky, but perhaps the `start_date` and `publish_date` constraint need not be mandatory for deactivation policies. 

### Is this a breaking change

A breaking change would require consumers or implementors of the API to modify their code for it to continue to function (ex: renaming of a required field or the change in data type of an existing field). A non-breaking change would allow existing code to continue to function (ex: addition of an optional field or the creation of a new optional endpoint). 

 * No, not breaking

### Impacted Spec

For which spec is this feature being requested?

 * `policy`

### Describe alternatives you've considered

We could maintain the status quo but it feels a little bit incorrect.

**Comment by schnuerle** [comment]
It does seem like an exception could be made if a policy is an error or mistake. I know @avatarneil and @marie-x and @jean-populus may have thoughts on this.
