### ISSUE TITLE
[Question]: Handling replacement of geographies

### ISSUE THREAD

**Issue by bhargav-lime** [openmobilityfoundation/mobility-data-specification#791]
In the [geographies schema](https://github.com/openmobilityfoundation/mobility-data-specification/blob/main/geography/README.md#geography-fields), I can see that a geography can replace previous geographies.
Is that replacement effective immediately? The Spec verbiage is not clear on this one.

This can help me determine which geographies will be used to compute data and prepare the response.

**Comment by schnuerle** [comment]
I think it's effective immediately. Asking @marie-x for their opinion.

**Comment by schnuerle** [comment]
> As currently written, yes, it's effective immediately. Do you think we should have `publish_date` and a separate `effective_date` like Policy does?

Those two fields are in there now for Geographies. 

Maybe all we need is a line saying geographies referencing others with prev_geographies immediately replace the previous ones.

**Comment by marie-x** [comment]
Updated my comment.  I think _maybe_ we can add a line of clarification to the spec.

**Comment by schnuerle** [comment]
If anyone has an idea of how to word that sentence and where to put it please share.

**Comment by schnuerle** [comment]
We added some clarification for this in a new "[Updating or Ending Policies](https://github.com/openmobilityfoundation/mobility-data-specification/tree/dev/policy#updating-or-ending-policies)" section in Policy.
