### ISSUE TITLE
Reporting tip-over scooters via MDS

### ISSUE THREAD

**Issue by JulianMiamiDade** [openmobilityfoundation/mobility-data-specification#794]
### Is your feature request related to a problem? Please describe.

Yes, I have asked my providers to help us trouble shoot policy for tip over  recognition through MDS. None of the companies seem to have an easy way to share this data. I wanted to know if there is any way to pilot it in small scale and in a way that contributes to the OMF path for the development of the standards.  

### Describe the solution you'd like

We would like to add data fields to the Micromobility MDS Agency Specification that can represent if a scooter's current state is upright or if its current state is tipped over.  

### Is this a breaking change

I'm not sure

### Impacted Spec

For which spec is this feature being requested?

 * `agency`

### Describe alternatives you've considered

Receiving weekly reports from individual providers.

**Comment by schnuerle** [comment]
We have talked about this some before. I think it could go in the /vehicles endpoint as a field with some name like 'orientation'. We would need to hear from operators about what type of data they have access to and what is its reliability? Is it a degree number around tilt, or a flag of tipped over or not, or something else? Then we can see how to include it as a new field.

**Comment by HiGregory** [comment]
Hi @JulianMiamiDade,

We did this work with the City of Miami through an API endpoint that was able to pull from various sources and Operators the status of changes. Some opt to do like @schnuerle mentioned adding it through /vehicles endpoints.

Here is a case study on how we helped the [City of Miami.](https://datagovs.docsend.com/view/42z4568x6mffygbd) Let me know if you are open to getting support on this and using ML to detect status changes of scooters.

**Comment by JulianMiamiDade** [comment]
Thanks @schnuerle, we are working with at least one of the vendors to trouble shoot this as an MDS policy. Vehicle endpoint is the preliminary route we set. We will hopefully answer some of those questions. I will keep you posted.                                                                                                     
                                                                                                                                                                                              @HiGregory that's great. We are getting data through agency API! Just looking for best approach to transmit the tip over data specifically. Was there a specific standard vetted in Miami for tip over data? Please let me know. Thank you so much.

**Comment by HiGregory** [comment]
Hi @JulianMiamiDade - custom model built for Miami's specific public right of way need for Tip / Scooter.

**Comment by schnuerle** [comment]
One of our new members Drover has a solution to this (that some operators are currently using) and I think they would like to see this added as well, so they may want to weigh in soon.

**Comment by JulianMiamiDade** [comment]
@schnuerle great, thanks so much! I had a conversation with Alex (Drover) at Comotion about this. We'll stay tuned for updates!

**Comment by schnuerle** [comment]
If we would like this in MDS 2.0, we need some feedback and suggestions to make it happen. It affects some of the #506 work based on where it should be added (telemetry, or only when not on trip?).

**Comment by droverai** [comment]
Drover PathPilot can send an event when the scooter gets tipped over. Here event would mean one-off telemetry to the provider whenever tip over status is toggled i.e. scooter is tipped over or put back on the stand. 

`"tipped_over": true` or `"tipped_over": false`  

From MDS standpoint, we see that there's suggestion to add the field to "Vehicle" endpoint. Would it make sense to add an event when tip over occurs i.e. `/events`?

**Comment by schnuerle** [comment]
Thank you for the feedback! 

`/vehicles` is getting [renamed](https://docs.google.com/document/d/134DrPFjSpapW1auTT2M_BuL2E9tdO1At0yu6VII1cPA/edit#heading=h.pzoobxt55yvu) `/devices` in 2.0. So we'll see about adding it here when @marie-x gets the draft done.

For `/events`, I don't think we need a tip over event and/or state to move in and out of. That's a bit different than what the state machine was intended for.

**Comment by schnuerle** [comment]
Please review the new `tipped_over` field in the Trips data type object ASAP:

https://github.com/openmobilityfoundation/mobility-data-specification/blob/feature-scooter-sensors/data-types.md#telemetry

Field | Type | Required/Optional | Field Description
-- | -- | -- | --
| `tipped_over`     | Boolean         | Required if Known      | If detectable and known, is the device tipped over or not? Default is 'false'. |

**Comment by schnuerle** [comment]
Complete with #829.
