### ISSUE TITLE
Remove Bolt Mobility from Providers CSV

### ISSUE THREAD

**Issue by HiGregory** [openmobilityfoundation/mobility-data-specification#799]
**Describe the issue**
Bolt Micro Mobility has reportedly ceased operation as observed by DataGovs MDS Monitoring as well as other 
news sources. Can we remove them from the Provider CSV? 

**To Reproduce**
Try using the MDS feed or GBFS feed available. 

**Expected behavior**
It won't work.

**Additional context**
https://www.micromobility.com/post/bolt-mobility-statement-august-3rd-2022

**Comment by schnuerle** [comment]
We have not removed any providers from the list. Their information and/or UUIDs may still be used in existing user code or collected data from cities, agencies, or researchers, so we keep them visible.
