### ISSUE TITLE
Add a "Data Provider UUID" to MDS

### ISSUE THREAD

**Issue by schnuerle** [openmobilityfoundation/mobility-data-specification#805]
### Is your feature request related to a problem? Please describe.

Per discussions around Modes in general and passenger services scenarios in particular, it is essential for some cities like SFMTA to get an ID around who is running the MDS feed, eg, who is the data provider. Traditionally this has been the operator of the service, but in micromobility recently and in other new modes there is also a hardware/software data solution provider filling the data needs for companies.

This new field will be part of MDS in most endpoints for agencies to consume where provider_id exists now. Here are the commit where this has been added as part of the #801 work:

- [Added data_provider_id to stops](https://github.com/openmobilityfoundation/mobility-data-specification/pull/801/commits/dbacc9c921ff308eb4504834df0d2bc641daaeaa)
- [Updated provider using mds](https://github.com/openmobilityfoundation/mobility-data-specification/pull/801/commits/fc30413dc99d2e9a19f45e2dbed4c8127f4ff1ea)
- [Added data_provider_id to Provider](https://github.com/openmobilityfoundation/mobility-data-specification/pull/801/commits/9b61d02e4aeaf7c2ab1e60ad11e4ace69eb4959b)
- [Added data_provider_id to Agency](https://github.com/openmobilityfoundation/mobility-data-specification/pull/801/commits/ab4f3294cc7a4b77b6eb52173e6579eda72e06ac)

It is suggested to add this as part of the Modes work, but I wanted to create this issue to make sure the concept and discussions are captured accurately. 

### Is this a breaking change

 * No, not breaking

### Impacted Spec

For which spec is this feature being requested?

 * `agency`
 * `provider`

### Describe alternatives you've considered

We could put this only in trips, or only in a certain mode, but I think this is important enough to put in the MDS base setup so it's available in all relevant endpoints for all modes. 

### Additional context

We created a similar field when building CDS 1.0, where it's important to know both the operator (who is using the curb) and the data provider (who is sending the data, which could be the operator or a company running a sensor).

**Comment by pierre-bouffort** [comment]
This looks good to me. A fairly simple change to implement really.

**Comment by schnuerle** [comment]
Added along with work in #801
