### ISSUE TITLE
Add Provider ID: [Telofun]

### ISSUE THREAD

**Issue by SamerAtawna** [openmobilityfoundation/mobility-data-specification#827]
**Note:** See the [Adding an MDS Provider ID](https://github.com/openmobilityfoundation/mobility-data-specification/wiki/Adding-an-MDS-Provider-ID) page for more help.

Opening this issue will allow you as a mobility service provider get an official provider ID for use across MDS globally.

**Fields needed from you for the [providers.csv file](https://github.com/openmobilityfoundation/mobility-data-specification/blob/main/providers.csv).**

_All fields are required._

1. **provider_name** - Short name of your company.
   - Telofun
1. **provider_id** - A random UUID version 4. There are lots of way to generate a unique UUID, like using this [website](https://www.uuidgenerator.net/version4).
   - 3dd253d3-557c-4fcb-98da-9af3edeaaae6
1. **url** - URL to the home page of your company.
   - https://www.tel-o-fun.co.il/
1. **mds_api_url** - Full https:// URL where your root MDS feeds are located.
   - https://mds.fsmctmobility.com/api/mds/v1/
1. **gbfs_api_url** - Full https:// URL where your public GBFS feeds are located.
   - ...

Additionally, please provide your name and role within your agency to help with verification.
Samer, Developer

**Comment by schnuerle** [comment]
Added with PR #831
