### ISSUE TITLE
Add Provider ID: Gbike

### ISSUE THREAD

**Issue by gbike-charles** [openmobilityfoundation/mobility-data-specification#839]
1. **provider_name** - Gbike
1. **provider_id** - a50b796e-bca2-11ed-afa1-0242ac120002
1. **url** - https://gcoo.io
1. **mds_api_url** - https://mds.gcoo.io
1. **gbfs_api_url** - https://mds.gcoo.io/gbfs

Additionally, please provide your name and role within your agency to help with verification.

Charles Chong, Software Engineer, Gbike Inc.

**Comment by schnuerle** [comment]
Thank you I will add this shortly and include it in the MDS 2.0 release.

**Comment by schnuerle** [comment]
Hi this has been [added in this commit](https://github.com/openmobilityfoundation/mobility-data-specification/pull/837/commits/22531d3285d079012383c2afb15c07dcc5ffa698). Thanks!

**Comment by gbike-charles** [comment]
> Hi this has been [added in this commit](https://github.com/openmobilityfoundation/mobility-data-specification/pull/837/commits/22531d3285d079012383c2afb15c07dcc5ffa698). Thanks!

Thanks!

**Comment by gbike-charles** [comment]
Is there any difference of being added in `release-2.0.0` vs in `dev` branch directly? I looked at similar requests in the past and they seemed to get added in `dev` directly. What timeline can we expect to be added as provider in `dev`?

**Comment by schnuerle** [comment]
Since we are in the last week of board approval for MDS 2.0, I put it in the release branch so as to avoid any downstream issues when merging the approved release back to dev then main. You can consider it the same and feel free to reference it now and it will be in both main and dev soon.

**Comment by gbike-charles** [comment]
> Since we are in the last week of board approval for MDS 2.0, I put it in the release branch so as to avoid any downstream issues when merging the approved release back to dev then main. You can consider it the same and feel free to reference it now and it will be in both main and dev soon.

Awesome. Thanks.
