### ISSUE TITLE
Provider and Policy GET data payloads vs. other data payloads

### ISSUE THREAD

**Issue by thekaveman** [openmobilityfoundation/mobility-data-specification#841]
## Issue

[Provider](https://github.com/openmobilityfoundation/mobility-data-specification/tree/release-2.0.0/provider#responses-and-error-messages) defines the data payload under the `data` top-level key, with an endpoint-specific key that holds the array of items:

```jsonc
{
    "version": "2.0.0",
    "data": {
        "vehicles": [
             // vehicle objects here
         ]
     }
}
```

This differs from e.g. Agency and Geographies, which define their GET payloads as top-level keys on their own, without the addition of the `data` layer:

```jsonc
{
    "version": "2.0.0",
    "vehicles": [
        // vehicle objects here
     ]
}
```

## Suggestion

Align Provider with the other APIs, by removing the additional `data` layer in the response payload, and returning the actual data items as a top-level key, like in Agency and Geographies.

**Comment by marie-x** [comment]
Agree with @thekaveman

**Comment by thekaveman** [comment]
### Policy

Defines it like Provider does, with a top-level [`data` key](https://github.com/openmobilityfoundation/mobility-data-specification/blob/release-2.0.0/policy/README.md#schema):

```jsonc
{
  "version": "x.y.z",
  "updated": 1570035222868,
  "data": {
     "policies": [ ... ]
  }
}
```

Suggest to change this to the same style as we are talking about here for Provider.

### Jurisdiction

Defines it like Agency and Geographies, at the top-level (based on what is shown in [the examples](https://github.com/openmobilityfoundation/mobility-data-specification/tree/release-2.0.0/jurisdiction/examples)):

```jsonc
{
    "version": "1.2.0",
    "updated": "1570035222868",
    "end_date": "1570035222868",
    "jurisdictions": [ ... ]
}
```

This is the style we should align Provider and Policy to.

### Metrics

Everything is at the top-level and the [response format](https://github.com/openmobilityfoundation/mobility-data-specification/blob/release-2.0.0/metrics/README.md#response-schema) is pretty different from other MDS APIs.

No need to change anything here.

**Comment by thekaveman** [comment]
This is being handled in OpenAPI in openmobilityfoundation/mds-openapi#6

**Comment by schnuerle** [comment]
I will work to make this change in the MDS spec.

**Comment by schnuerle** [comment]
Fixed this by removing the data level across Provider and Policy in this [commit](https://github.com/openmobilityfoundation/mobility-data-specification/pull/837/commits/c70c6020a6adb33dee4df71e8d02003a4de47fba). Can close this issue upon @thekaveman review.

**Comment by thekaveman** [comment]
Yep looks good 👍
