### ISSUE TITLE
Policy/Geography response.updated vs. other response.last_updated

### ISSUE THREAD

**Issue by thekaveman** [openmobilityfoundation/mobility-data-specification#842]
## Issue

[Policy](https://github.com/openmobilityfoundation/mobility-data-specification/blob/release-2.0.0/policy/README.md#schema) describes its schema with a top-level `updated` key with its value "a timestamp indicating the last time the data was updated". [Geography does the same](https://github.com/openmobilityfoundation/mobility-data-specification/tree/release-2.0.0/geography#file-format).

Other APIs like Provider describe [Data Latency Requirements](https://github.com/openmobilityfoundation/mobility-data-specification/blob/release-2.0.0/provider/README.md#data-latency-requirements) and use `last_updated` in the top-level response to indicate the same thing.

## Suggestion

Align on a single field name for all APIs.

**Comment by thekaveman** [comment]
Maybe since Policy and Geography already use `updated`, Provider is the outlier with `last_updated` and so we should align Provider to be the same as Policy/Geography?

In any case, as long as we align and use a consistent field name everywhere, the specific choice doesn't matter as much.

**Comment by schnuerle** [comment]
I think last_updated is the way to go, as we do in CDS now! https://github.com/openmobilityfoundation/curb-data-specification/blob/main/general-information.md#rest-endpoints

**Comment by marie-x** [comment]
Agree, `last_updated` everywhere.

**Comment by thekaveman** [comment]
Done for Geography in the spec in #858

**Comment by schnuerle** [comment]
I've updated MDS 2.0 with `last_updated` across [Policy](https://github.com/openmobilityfoundation/mobility-data-specification/pull/837/commits/729ea16b43d03d2883f9e27adb5a744e97ede4f4), [Geography](https://github.com/openmobilityfoundation/mobility-data-specification/pull/837/commits/50e3b0122868640a606a7f428a0347df96ec5396), [Jurisdiction](https://github.com/openmobilityfoundation/mobility-data-specification/pull/837/commits/b6476e393f8c506cf0e69a3bbdc0bc0207f34a1c), and [Stops](https://github.com/openmobilityfoundation/mobility-data-specification/pull/837/commits/da015b7e52626d087e022c0f5766701654225ed2) (in data types).

Ready to close this issue when @thekaveman does the updates for OpenAPI.

**Comment by thekaveman** [comment]
Done for Policy OpenAPI in https://github.com/openmobilityfoundation/mds-openapi/pull/20
