### ISSUE TITLE
Car share event types

### ISSUE THREAD

**Issue by thekaveman** [openmobilityfoundation/mobility-data-specification#843]
## Cancellation types issue

In the [`car-share` mode, under Event Types](https://github.com/openmobilityfoundation/mobility-data-specification/blob/release-2.0.0/modes/car-share.md#event-types), we have the following _cancellation_ types:

* driver_cancellation
* passenger_cancellation
* provider_cancellation

In the [Trip ID Requirements](https://github.com/openmobilityfoundation/mobility-data-specification/blob/release-2.0.0/modes/car-share.md#trip-id-requirements) we see these _cancellation_ types:

* driver_cancellation
* customer_cancellation
* provider_cancellation

**Which one is correct (or are both?) for `car-share`**:

* customer_cancellation
* passenger_cancellation

## Trip types issue

[Trip ID Requirements](https://github.com/openmobilityfoundation/mobility-data-specification/blob/release-2.0.0/modes/car-share.md#trip-id-requirements) lists `trip_pause` and `trip_resume`.

[Event Types](https://github.com/openmobilityfoundation/mobility-data-specification/blob/release-2.0.0/modes/car-share.md#event-types) only lists `trip_resume`, omitting `trip_pause`

Presumably `trip_pause` should be an allowed Event Type here.

**Comment by thekaveman** [comment]
> I think passenger_cancellation is wrong for car share and only applies to passenger services.

Got it, so the correct list for car share is:

* driver_cancellation
* customer_cancellation
* provider_cancellation

> Yes and trip_pause should also be added to possible events.

Done.

**Comment by thekaveman** [comment]
This is being handled in OpenAPI in https://github.com/openmobilityfoundation/mds-openapi/issues/6

**Comment by schnuerle** [comment]
I will make the change to the list for car share here.
https://github.com/openmobilityfoundation/mobility-data-specification/blob/release-2.0.0/modes/car-share.md#event-types

**Comment by schnuerle** [comment]
Updated car share to change references to passenger to customer instead in this [commit](https://github.com/openmobilityfoundation/mobility-data-specification/pull/837/commits/a0b646679477c68a910abf0efc1ec082256ffb65), and updated the state machine diagram [here](https://github.com/openmobilityfoundation/mobility-data-specification/pull/837/commits/218b0ec13e65a3e6113c2cc48f722113c62c7818). Ready to close issue on confirmation by @thekaveman.

**Comment by thekaveman** [comment]
@schnuerle I think we still need this update: 

> `trip_pause` should also be added to possible events.

**Comment by schnuerle** [comment]
Looking at it I actually think trip_pause should not be in Car Share. The 4 listed should work fine. I think it need to be removed from the Trip ID Requirements list here instead:  https://github.com/openmobilityfoundation/mobility-data-specification/blob/release-2.0.0/modes/car-share.md#trip-id-requirements

Car Share

	•	trip_end
	•	trip_resume
	•	trip_start
	•	trip_stop	

Micro 

	•	trip_cancel
	•	trip_end
	•	trip_start

Robots

	•	trip_end
	•	trip_resume
	•	trip_start
	•	trip_pause

Passenger

	•	trip_end
	•	trip_resume
	•	trip_start
	•	trip_stop

All Available

Field | Description
-- | --
trip_cancel | Cancel trip
trip_end | End trip
trip_enter_jurisdiction | Trip enters a jurisdiction
trip_leave_jurisdiction | Trip leaves a jurisdiction
trip_pause | Pause trip temporarily but do not end trip
trip_resume | Resume trip
trip_start | Start trip
trip_stop | Stop trip

**Comment by schnuerle** [comment]
Removed trip_pause from car share [here](https://github.com/openmobilityfoundation/mobility-data-specification/pull/837/commits/d8aa21e5f6e1f2950dfd04cf538a54b9f166baa4).
