### ISSUE TITLE
Stop.rental_methods vs. fare_attributes.payment_type

### ISSUE THREAD

**Issue by thekaveman** [openmobilityfoundation/mobility-data-specification#844]
## Issue

[Stops](https://github.com/openmobilityfoundation/mobility-data-specification/blob/release-2.0.0/data-types.md#stops) defines the `rental_methods` field as follows:

> `Enum[]`: List of payment methods accepted at stop, see [GBFS Rental Methods](https://github.com/NABSA/gbfs/blob/master/gbfs.md#station_informationjson)

`GBFS Rental Methods` as of April 2023 are:

- `key`
- `creditcard`
- `paypass`
- `applepay`
- `androidpay`
- `transitcard`
- `accountnumber`
- `phone`

Further, some modes support the `fare_attributes.payment_type` field, with a different list of options and the the following variation:

| | [`care-share`](https://github.com/openmobilityfoundation/mobility-data-specification/blob/release-2.0.0/modes/car-share.md#fare-attributes) | [`delivery-robots`](https://github.com/openmobilityfoundation/mobility-data-specification/blob/release-2.0.0/modes/delivery-robots.md#fare-attributes) | [`passenger-services`](https://github.com/openmobilityfoundation/mobility-data-specification/blob/release-2.0.0/modes/passenger-services.md#fare-attributes) |
| - | - | - | - |
| `cash` | x | x | x |
| `credit_card` | x |  | x |
| `mobile` | x | x | x |
| `voucher` | x | x | x |
| `paratransit` |  | x | x |
| `no payment` | x | x | x |
| `test` | x | x | x |

**Comment by thekaveman** [comment]
> What are the values for micromobility?

The `micromobility` mode does not use the `fare_attributes` property of `trip`: https://github.com/openmobilityfoundation/mobility-data-specification/blob/release-2.0.0/modes/micromobility.md#fare-attributes

**Comment by thekaveman** [comment]
@schnuerle in thinking about adding `phone` and changing `mobile` to `mobile_app`... It still doesn't seem clear to me, how does `phone` differ from `mobile_app`?

**Comment by schnuerle** [comment]
Phone is when a reservation is made via a phone call, to a phone number. So it's different from a mobile app.

**Comment by schnuerle** [comment]
Payment types are aligned in this [commit](https://github.com/openmobilityfoundation/mobility-data-specification/pull/837/commits/94af08efac54bcd844a2b84ff2e37d0371ed04a1).  Ready to close this issue when confirmed by @thekaveman.

**Comment by thekaveman** [comment]
Looks good 👍
