### ISSUE TITLE
Event types missing from aggregate list

### ISSUE THREAD

**Issue by thekaveman** [openmobilityfoundation/mobility-data-specification#845]
The list of all `event_type` here: https://github.com/openmobilityfoundation/mobility-data-specification/blob/release-2.0.0/modes/event_types.md is incomplete based on those gathered from the various mode state machine transition tables -- 5 types are missing.

Here is the full list of `event_type`, with missing types marked with an asterisk `*`:

- agency_drop_off
- agency_pick_up
- battery_charged
- battery_low
- changed_geographies
- charging_end
- charging_start
- comms_lost
- comms_restored
- compliance_pick_up
- customer_cancellation
- decommissioned
- driver_cancellation
- fueling_end
- fueling_start
- located
- maintenance
- maintenance_end
- maintenance_pick_up
- not_located
- off_hours
- on_hours
- order_drop_off
- order_pick_up
- passenger_cancellation`*`
- provider_cancellation
- provider_drop_off
- rebalance_pick_up
- recommission`*`
- remote_end
- remote_start
- reservation_cancel
- reservation_start
- reservation_stop
- service_end`*`
- service_start`*`
- system_resume
- system_suspend
- trip_cancel
- trip_end
- trip_enter_jurisdiction
- trip_leave_jurisdiction
- trip_pause
- trip_resume
- trip_start
- trip_stop`*`
- unspecified

**Comment by marie-x** [comment]
Bless you for your attention to detail.

**Comment by thekaveman** [comment]
Fixed in #849
