### ISSUE TITLE
Trip and fare attributes optional or required?

### ISSUE THREAD

**Issue by thekaveman** [openmobilityfoundation/mobility-data-specification#846]
Certain modes have Trip and Fare attributes that are required, while the parent object itself is optional, e.g. in [`car-share`](https://github.com/openmobilityfoundation/mobility-data-specification/blob/release-2.0.0/modes/car-share.md#trip-attributes)

```jsonc
// a trip record
{
   // other trip fields

   "trip_attributes": {  // <-- optional trip property
      "reservation_type": "app" // <-- required trip_attributes property
   },

   // other trip fields
}
```

As it is worded now, `reservation_type` is only required _if_ `trip_attributes` are provided, and `trip_attributes` itself is not required in a `trip` -- is this the correct interpretation?

**Comment by schnuerle** [comment]
Yes that's the intention, it's required if trip_attributes are used.

But are trip attributes required for the other modes? Maybe they should be required.
