### ISSUE TITLE
/vehicles in MDS 2.0

### ISSUE THREAD

**Issue by sven4all** [openmobilityfoundation/mobility-data-specification#857]
### Is your feature request related to a problem? Please describe.

In MDS 2.0 a lot of information is removed from vehicle object in the /provider/agency endpoint, but at the same time the documenatation of the /provider/agency endpoint doesn't seems te be upgraded  yet https://github.com/openmobilityfoundation/mobility-data-specification/blob/release-2.0.0/provider/README.md#vehicles, a comparison is made with /free_bike_status of GBFS for example, while the goal of this endpoint seems to be completely changed with the 2.0 version. 

### Describe the solution you'd like

We develop an open-source dashboard for municipalities within the Netherlands and relly heavily on this /vehicles endpoint https://dashboarddeelmobiliteit.nl/. We therefor think we should reconsider removing the status and location information from this endpoint. Another option would be to have a get all on the vehicle_status endpoint. We think that as a dashboard you always want to retreive all the vehicle_statuses at once, and therefor don't see any benefit at all in the pagination that is suggested. If there will be pagination we want to have a minimal number of vehicles per page of 10000 to prevent performance problems if you need to fetch 30000 vehicles for example with a page size of 20 (we have seen this in the past). 

### Is this a breaking change

This change is currently not breaking, because 2.0 is not release yet. 

### Impacted Spec

 * `provider`

**Comment by schnuerle** [comment]
Hi @sven4all could you describe this in a different way? I'm not sure I follow what you are asking for. Do you want less fields like no status and location from vehicles? Or do you want to get all the data at once and so pagination is a problem? Or are these both separate concerns for you?

Which documentation for Provider and Agency endpoints is not updated yet?

**Comment by sven4all** [comment]
Hi Michael,

It's indeed a little bit related.

I feel that the new /vehicle endpoint is about details of vehicles that
don't change that often. But in the documentation still PROW (a realtime
state) is referenced. But at the same time all fields that describe the
state of that vehicle are removed.

I think that we really need to consider if we splitting this endpoint up in
seperate parts is really needed and what problem we are solving with it.

Pagination is maybe a seperate problem that is also in the current
specification but in my opinion MDS should be opinionated about minimal
page size because a too small page size is not usable for aggregators who
wants to fetch all the data every 30s.

I am currently on a holiday and do only have my phone on me, so it's a
little bit difficult to react on all your questions in detail. Is it ok if
I react later on it?

Best regards,

Sven

Op do 4 mei 2023 17:43 schreef Michael Schnuerle ***@***.***>:

**Comment by jiffyclub** [comment]
I agree about the pagination, it can add a lot of time to getting data when pages are small, especially if each individual request is slow.

**Comment by schnuerle** [comment]
@sven4all Take a look at the discussion on #862. I think it clarifies that the real time information you are looking for is still in 2.0, just in a different way. 

It's too late for changes for 2.0, but we can continue to discuss here for the future.

**Comment by sven4all** [comment]
Yes this will work, but make things a little bit more complicated both for
consumers and producers.

The information you are referencing to in the tickets is clear, but my
problem right now is that there is also a lot of old documentation floating
around. It's really important that it's clear that that documentation is
outdated and that the documentation about MDS 2.0 contains the information
that you included in the referenced ticket.

Besides that we should discuss if we want pagination in /vehicles/status
and if we think that that adds value if we agree MDS should be opinionated
about a minimal page size.

Op vr 5 mei 2023 23:01 schreef Michael Schnuerle ***@***.***>:

**Comment by sven4all** [comment]
@jiffyclub @schnuerle how can we proceed with this discussion?

**Comment by jiffyclub** [comment]
#882 clarifies the documentation of the vehicles endpoints in the provider spec and is slated for MDS 2.0.1.

**Comment by schnuerle** [comment]
Resolved with #882
