### ISSUE TITLE
MDS 2.0 - telemetry fields trip_ids/journey_id should correspond to the event 

### ISSUE THREAD

**Issue by lastalfriday** [openmobilityfoundation/mobility-data-specification#859]
Extracted from another issue [here](https://github.com/openmobilityfoundation/mobility-data-specification/issues/847)

**EDIT**
I'm a bit confused. I just noticed that there are some differences between the *tag* `2.0.0-rc1` and the *branch* `release-2.0.0`. So I'm splitting this issue into 1 and 2, as they are related (instead of making another issue)

# 1 - Which is right

https://github.com/openmobilityfoundation/mobility-data-specification/blob/release-2.0.0/data-types.md#events
(I'm guessing this is right, but why was `journey_id`  removed? If it's relevant for telemetry, is it not relevant for events?)

![image](https://user-images.githubusercontent.com/40355961/235686011-7880c89d-6b4d-4ff2-be7e-335538c4e67f.png)

https://github.com/openmobilityfoundation/mobility-data-specification/blob/2.0.0-rc1/data-types.md#events

![image](https://user-images.githubusercontent.com/40355961/235686126-0340d328-fb1a-4973-9228-c1ba51cdff36.png)

# 2 - Telemetry fields that should be optional

The fields `trip_ids` and `journey_id` should be the same for telemetry and events, and I do believe events has it correct (these fields must be required **if available** and optional)

This diff/error is probably a cut n paste error?

![image](https://user-images.githubusercontent.com/40355961/235682297-bc2090e4-ff5f-4c4c-8f67-5419fc60de03.png)

**Comment by thekaveman** [comment]
@lastalfriday The branch `release-2.0.0` should be the base for any issues/review for MDS 2.0 as it is being updated continuously until the release.

The tag `2.0.0-rc1` was made back in Feb as part of the [MDS Release Process](https://github.com/openmobilityfoundation/governance/blob/main/technical/ReleaseGuidelines.md#preparing-a-release-candidate).
