### ISSUE TITLE
MDS Provider Id Registration

### ISSUE THREAD

**Issue by Sharnam220** [openmobilityfoundation/mobility-data-specification#861]
SURF,micromobility,66c43ccb-f9f9-4f70-9707-37301b9f49a8,https://www.surfingscooters.com,https://api.app.surf/mds,https://api.app.surf/gbfs/en

**Comment by schnuerle** [comment]
Thank you, SURF has been added in this [commit](https://github.com/openmobilityfoundation/mobility-data-specification/pull/837/commits/46a1ab61ee74e7d1c03f8351a1f6e203dd6c1e9c)!
