### ISSUE TITLE
Correction of description vehicle events (car sharing)

### ISSUE THREAD

**Issue by bergenklem** [openmobilityfoundation/mobility-data-specification#868]
Of what we can see, the table for [vehicle events in [car sharing mode](https://github.com/openmobilityfoundation/mobility-data-specification/blob/main/modes/car-share.md#vehicle-states-events) needs an update, as they right now points towards actions that are more in relation to taxi services (and/or autonomous vehicles) than a car sharing operation as of today.

![event types description](https://github.com/openmobilityfoundation/mobility-data-specification/assets/134277360/39cb85a2-e656-4052-8ff3-13296a4b02ec)

**Comment by schnuerle** [comment]
Yes this looks like just a carry over typo. So this can be fixed in the next release, maybe a 2.0.1 [patch](https://github.com/openmobilityfoundation/governance/blob/main/technical/ReleaseGuidelines.md#versioning) release.

**Comment by schnuerle** [comment]
If you can make a PR for this change, that would be helpful, and you'd be listed as a GitHub contributor.  We are looking at creating a 2.0.1 release soon for all open issues and PRs tagged with the [2.0.1 Milestone](https://github.com/openmobilityfoundation/mobility-data-specification/milestone/16). If not I will create the PR.

**Comment by schnuerle** [comment]
Closed with #881
