### ISSUE TITLE
Reports endpoint - START_DATE clarification

### ISSUE THREAD

**Issue by Mu-yi-Zhou** [openmobilityfoundation/mobility-data-specification#876]
Please clarify START_DATE of the REPORTS endpoint https://github.com/openmobilityfoundation/mobility-data-specification/blob/main/data-types.md#reports

'Start date of trip the data row, ISO 8601 date format, i.e. YYYY-MM-DD' looks confusing.

**Comment by schnuerle** [comment]
I think there is a typo there, it should say "Start date of the [Trip](https://github.com/openmobilityfoundation/mobility-data-specification/blob/main/data-types.md#trips) data row, in ISO 8601 date format, i.e. YYYY-MM-DD". We can correct in the 2.0.1 release.

**Comment by schnuerle** [comment]
If you can make a PR for this change, that would be helpful, and you'd be listed as a GitHub contributor.  We are looking at creating a 2.0.1 release soon for all open issues and PRs tagged with the [2.0.1 Milestone](https://github.com/openmobilityfoundation/mobility-data-specification/milestone/16). If not I will create the PR.

**Comment by schnuerle** [comment]
I can handle making this change when we finalize the 2.0.1 release work.

**Comment by schnuerle** [comment]
Closed with PR #883 883
