### ISSUE TITLE
What vehicles are included in the MDS 2.0 /vehicles endpoint?

### ISSUE THREAD

**Issue by jiffyclub** [openmobilityfoundation/mobility-data-specification#879]
In MDS 2.0 the `/vehicles` endpoint contains static vehicle information that could be required for vehicles deployed years in the past. However, the [documentation](https://github.com/openmobilityfoundation/mobility-data-specification/tree/2.0.0/provider#vehicles) reads:
> The /vehicles is a near-realtime endpoint and returns the current status of vehicles in an agency's [Jurisdiction](https://github.com/openmobilityfoundation/mobility-data-specification/blob/2.0.0/general-information.md#definitions) and/or area of agency responsibility. All vehicles that are currently in any [vehicle_state](https://github.com/openmobilityfoundation/mobility-data-specification/blob/2.0.0/modes#vehicle-states) should be returned in this payload. Since all states are returned, care should be taken to filter out states not in the [PROW](https://github.com/openmobilityfoundation/mobility-data-specification/blob/2.0.0/general-information.md#definitions) if doing vehicle counts. For the states elsewhere and removed which include vehicles not in the [PROW](https://github.com/openmobilityfoundation/mobility-data-specification/blob/2.0.0/general-information.md#definitions) but provide some operational clarity for agencies, these must only persist in the feed for 90 minutes before being removed.

This is [carryover language from MDS 1.x](https://github.com/openmobilityfoundation/mobility-data-specification/tree/1.2.0/provider#vehicles) and I'm curious what the expectations are for the MDS 2.0 `/vehicles` endpoint (distinct from the `/vehicles/status` endpoint). Should it contain every vehicle ever deployed in a jurisdiction? If it is only expected to contain currently deployed vehicles (like the MDS 1.x `/vehicles` endpoint), what's the procedure for getting vehicle information for historically deployed vehicles? Request it one vehicle at a time via `/vehicles/{device-id}`?

And then thinking about the relationship between MDS 2.0 `/vehicles` and `/vehicles/status`, my instinct is that we should require that at a minimum the `/vehicles` endpoint should always return the same vehicles as would be returned by `/vehicles/status` and document that requirement. But that still leaves the question of how to get vehicle information for historically deployed vehicles.

**Comment by schnuerle** [comment]
If you can make a PR for this change, that would be helpful, and you'd be listed as a GitHub contributor.  We are looking at creating a 2.0.1 release soon for all open issues and PRs tagged with the [2.0.1 Milestone](https://github.com/openmobilityfoundation/mobility-data-specification/milestone/16). If not I will create the PR.

**Comment by jiffyclub** [comment]
I can make a PR but I think there's an unresolved question here of what the `/vehicles` endpoint should return.

**Comment by jiffyclub** [comment]
See #882 for PR. I'm proposing this language for the `/vehicles` endpoint expectations:
> When `/vehicles` is called without specifying a device ID it should return every vehicle that has
ever been deployed in an agency's Jurisdiction and/or area of agency responsibility.

**Comment by schnuerle** [comment]
Resolved with #882
