### ISSUE TITLE
Reports endpoint - description of START_DATE

### ISSUE THREAD

**Issue by Mu-yi-Zhou** [openmobilityfoundation/mobility-data-specification#885]
### Is your feature request related to a problem? Please describe.

Description of START_DATE of Reports endpoint is not clear. 

### Describe the solution you'd like

Correct the description of START_DATE of Reports endpoint

### Is this a breaking change

A breaking change would require consumers or implementors of the API to modify their code for it to continue to function (ex: renaming of a required field or the change in data type of an existing field). A non-breaking change would allow existing code to continue to function (ex: addition of an optional field or the creation of a new optional endpoint). 

 * No, not breaking

### Impacted Spec

For which spec is this feature being requested?

 * `provider`

### Additional context

start_date | date | Start date of trip the data row, ISO 8601 date format, i.e. YYYY-MM-DD

[Link in spec](https://github.com/openmobilityfoundation/mobility-data-specification/blob/main/data-types.md#reports)

**Comment by schnuerle** [comment]
Hi do you just want to correct the typo, or do you need a different explanation of the start_date field?

To fix the typo, the description should read "Start date of the trip data row, ISO 8601 date format, i.e. YYYY-MM-DD".

**Comment by schnuerle** [comment]
Feel free to make a quick PR to fix this if you'd like credit in the 2.0.1 release, or I will make that PR for you this week.

**Comment by schnuerle** [comment]
Yes, this was fixed with https://github.com/openmobilityfoundation/mobility-data-specification/pull/883 and will show up in the main branch soon with our patch release.

**Comment by Mu-yi-Zhou** [comment]
Thank you Michael. Sorry I overlooked the emails in the past week.

Muyi

Michael Schnuerle ***@***.***> 于2023年12月18日周一 12:35写道：
