### ISSUE TITLE
Add Provider ID: Nextbike

### ISSUE THREAD

**Issue by kulovan** [openmobilityfoundation/mobility-data-specification#890]
**Note:** See the [Adding an MDS Provider ID](https://github.com/openmobilityfoundation/mobility-data-specification/wiki/Adding-an-MDS-Provider-ID) page for more help.

Opening this issue will allow you as a mobility service provider or data source provider to get an official provider ID for use across MDS globally.

**Fields needed from you for the [providers.csv file](https://github.com/openmobilityfoundation/mobility-data-specification/blob/main/providers.csv).**

_All fields are required._

1. **provider_name** - Nextbike.
1. **mode_id** - `micromobility`
1. **provider_id** - `31e54f5a-66c4-4a4c-bb6e-236351c90312`
1. **url** - https://www.nextbike.de
1. **mds_api_url** - https://platform-services.tier-services.io/data-sharing/mds/.
1. **gbfs_api_url** - `https://api.nextbike.net/maps/gbfs/v1/nextbike_<NETWORK-ID>/gbfs.json`

Additionally, please provide your name and role within your agency to help with verification.
   - Daniel Janko, Engineering Lead

**Comment by schnuerle** [comment]
Feel free to make a quick PR to fix this if you'd like credit in the 2.0.1 release, or I will make that PR for you this week.

**Comment by schnuerle** [comment]
Thank you I created PR #892 and added this to our development branch for inclusion in our 2.0.1 patch release.
