### ISSUE TITLE
Add Provider ID: Starship Technologies

### ISSUE THREAD

**Issue by rustam-starship** [openmobilityfoundation/mobility-data-specification#897]
**Note:** See the [Adding an MDS Provider ID](https://github.com/openmobilityfoundation/mobility-data-specification/wiki/Adding-an-MDS-Provider-ID) page for more help.

Opening this issue will allow you as a mobility service provider or data source provider to get an official provider ID for use across MDS globally.

**Fields needed from you for the [providers.csv file](https://github.com/openmobilityfoundation/mobility-data-specification/blob/main/providers.csv).**

_All fields are required._

1. **provider_name** - Starship Technologies
   - ...
1. **mode_id** - delivery-robots
   - ...
1. **provider_id** - 4a1524f3-8182-4b55-90c2-023c0cac84b9
   - ...
1. **url** - https://www.starship.xyz/
   - ...
1. **mds_api_url** - TBI
   - ...
1. **gbfs_api_url** - 
   - ...

Hey, my name is Rustam Kadyrov. I'm software engineer from Starship Technologies. Here is my email: rustam.kadyrov@starship.co.
I'd love to add Starship Technologies to providers list since I need to use the unique provider id. As soon as functionality completed I'll provide url in a separate PR.

**Comment by schnuerle** [comment]
I've created the PR for this here with #898. Please review for accuracy.

You may now use your provider_id - 4a1524f3-8182-4b55-90c2-023c0cac84b9 in development.

Please comment back here when your MDS URL stub is ready, and GBFS if you have it.

**Comment by rustam-starship** [comment]
I added comment to the PR

**Comment by schnuerle** [comment]
Merged to the dev branch. Thank you!
