### ISSUE TITLE
Add Provider ID: Flamingo

### ISSUE THREAD

**Issue by hynick4** [openmobilityfoundation/mobility-data-specification#907]
**Note:** See the [Adding an MDS Provider ID](https://github.com/openmobilityfoundation/mobility-data-specification/wiki/Adding-an-MDS-Provider-ID) page for more help.

Opening this issue will allow you as a mobility service provider or data source provider to get an official provider ID for use across MDS globally.

**Fields needed from you for the [providers.csv file](https://github.com/openmobilityfoundation/mobility-data-specification/blob/main/providers.csv).**

_All fields are required._

1. **provider_name** - Flamingo
1. **mode_id** - `micromobility`
1. **provider_id** - `a32f88c4-ad9b-4bf1-b5d8-e0262fa8a582`
1. **url** - [https://rideflamingo.com/](https://rideflamingo.com/)
1. **mds_api_url** - [https://data.rideflamingo.com/mds/](https://data.rideflamingo.com/mds/)
1. **gbfs_api_url** - [https://data.rideflamingo.com/gbfs/3/manifest.json](https://data.rideflamingo.com/gbfs/3/manifest.json)

Additionally, please provide your name and role within your agency to help with verification.
   - Nick Hyland, CTO at Flamingo (nick@rideflamingo.com)

**Comment by schnuerle** [comment]
@mplsmitch will create a PR and add it to the dev branch of the spec. You can start using your ID now.

**Comment by schnuerle** [comment]
Thank you we've now got this in the `dev` branch [here](https://github.com/openmobilityfoundation/mobility-data-specification/blob/dev/providers.csv).
