### ISSUE TITLE
Add Provider ID: 3km

### ISSUE THREAD

**Issue by charleREN** [openmobilityfoundation/mobility-data-specification#912]
**Note:** See the [Adding an MDS Provider ID](https://github.com/openmobilityfoundation/mobility-data-specification/wiki/Adding-an-MDS-Provider-ID) page for more help.

Opening this issue will allow you as a mobility service provider or data source provider to get an official provider ID for use across MDS globally.

**Fields needed from you for the [providers.csv file](https://github.com/openmobilityfoundation/mobility-data-specification/blob/main/providers.csv).**

_All fields are required._

1. **provider_name** -  3KM
2. **mode_id**  -  micromobility
3. **provider_id**  - fd32a231-f373-4049-9b73-14686a24ed06
4. **url** - https://ario.ai
5. **mds_api_url** - https://mds.ario.ai

Additionally, please provide your name and role within your agency to help with verification.
  
 my name is Xupeng Ren. I'm software engineer from 3KM. Here is my email: renxupeng@global.ario.ai

**Comment by schnuerle** [comment]
@mplsmitch has opened a pull request for you here #913.  

@charleREN do you have a GBFS feed to provide as well? See the [GBFS Requirement](https://github.com/openmobilityfoundation/mobility-data-specification?tab=readme-ov-file#gbfs-requirement).

**Comment by charleREN** [comment]
gbfs_api_url should remain empty as we do not provide this information.

**Comment by schnuerle** [comment]
Complete with #913
